<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.marketcetera</groupId>
    <artifactId>fix-parent</artifactId>
    <version>4.2.0-SNAPSHOT</version>
  </parent>
  <groupId>org.marketcetera</groupId>
  <artifactId>fix-rpc-core</artifactId>
  <version>4.2.0-SNAPSHOT</version>
  <name>FIX RPC Core</name>
  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>fix-api</artifactId>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>cluster-rpc-core</artifactId>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>rpc-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>0.6.1</version>
        <configuration>
          <!--
              The version of protoc must match protobuf-java. If you don't depend on
              protobuf-java directly, you will be transitively depending on the
              protobuf-java version that grpc depends on.
          -->
          <protocArtifact>com.google.protobuf:protoc:3.20.3:exe:${os.detected.classifier}</protocArtifact>
          <pluginId>grpc-java</pluginId>
          <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.53.0:exe:${os.detected.classifier}</pluginArtifact>
          <!-- Configure input and output directories -->
          <inputDirectories>
            <inputDirectory>src/main/proto</inputDirectory>
          </inputDirectories>
          <testInputDirectories>
            <testInputDirectory>src/test/proto</testInputDirectory>
          </testInputDirectories>
          <clearOutputDirectory>false</clearOutputDirectory>
          <attachProtoSources>true</attachProtoSources>
          <outputDirectory>${project.build.directory}/generated-sources/protobuf/java</outputDirectory>
          <outputTargetDirectory>${project.build.directory}/generated-sources/protobuf</outputTargetDirectory>
          <testOutputDirectory>${project.build.directory}/generated-test-sources/protobuf/java</testOutputDirectory>
          <testOutputTargetDirectory>${project.build.directory}/generated-test-sources/protobuf</testOutputTargetDirectory>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
              <goal>test-compile</goal>
              <goal>test-compile-custom</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <disableXmlReport>false</disableXmlReport>
          <forkCount>1</forkCount>
          <reuseForks>false</reuseForks>
          <argLine>${mvn.test.options}</argLine>
        </configuration>
      </plugin>
      
      <!-- Add generated source directories to build path -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-protobuf-sources</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/generated-sources/protobuf/java</source>
                <source>${project.build.directory}/generated-sources/protobuf/grpc-java</source>
              </sources>
            </configuration>
          </execution>
          <execution>
            <id>add-protobuf-test-sources</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/generated-test-sources/protobuf/java</source>
                <source>${project.build.directory}/generated-test-sources/protobuf/grpc-java</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
