//
// this file is automatically generated
//
package org.marketcetera.trade.pnl.event;

/* $License$ */

/**
 * Indicates that an existing position for a user has changed.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface PositionChangedEvent
        extends org.marketcetera.trade.pnl.HasPosition
{
}
