//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

/* $License$ */

/**
 * Creates new {@link SimpleUserTrade} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class SimpleUserTradeFactory
        implements UserTradeFactory
{
    /**
     * Create a new <code>SimpleUserTrade</code> instance.
     *
     * @return a <code>SimpleUserTrade</code> value
     */
    @Override
    public SimpleUserTrade create()
    {
        return new SimpleUserTrade();
    }
    /**
     * Create a new <code>SimpleUserTrade</code> instance from the given object.
     *
     * @param inObject a <code>SimpleUserTrade</code> value
     * @return a <code>SimpleUserTrade</code> value
     */
    @Override
    public SimpleUserTrade create(UserTrade inSimpleUserTrade)
    {
        return new SimpleUserTrade(inSimpleUserTrade);
    }
}
