//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

/* $License$ */

/**
 * Creates new {@link SimpleUserTrade} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class SimpleUserTradeFactory
        implements org.marketcetera.trade.pnl.UserTradeFactory
{
    /**
     * Create a new <code>org.marketcetera.trade.pnl.SimpleUserTrade</code> instance.
     *
     * @return a <code>org.marketcetera.trade.pnl.SimpleUserTrade</code> value
     */
    @Override
    public org.marketcetera.trade.pnl.SimpleUserTrade create()
    {
        return new org.marketcetera.trade.pnl.SimpleUserTrade();
    }
    /**
     * Create a new <code>org.marketcetera.trade.pnl.SimpleUserTrade</code> instance from the given object.
     *
     * @param inUserTrade an <code>org.marketcetera.trade.pnl.SimpleUserTrade</code> value
     * @return an <code>org.marketcetera.trade.pnl.SimpleUserTrade</code> value
     */
    @Override
    public org.marketcetera.trade.pnl.SimpleUserTrade create(org.marketcetera.trade.pnl.UserTrade inSimpleUserTrade)
    {
        return new org.marketcetera.trade.pnl.SimpleUserTrade(inSimpleUserTrade);
    }
}
