//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

/* $License$ */

/**
 * Creates new {@link SimpleProfitAndLoss} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class SimpleProfitAndLossFactory
        implements ProfitAndLossFactory
{
    /**
     * Create a new <code>SimpleProfitAndLoss</code> instance.
     *
     * @return a <code>SimpleProfitAndLoss</code> value
     */
    @Override
    public SimpleProfitAndLoss create()
    {
        return new SimpleProfitAndLoss();
    }
    /**
     * Create a new <code>SimpleProfitAndLoss</code> instance from the given object.
     *
     * @param inObject a <code>SimpleProfitAndLoss</code> value
     * @return a <code>SimpleProfitAndLoss</code> value
     */
    @Override
    public SimpleProfitAndLoss create(ProfitAndLoss inSimpleProfitAndLoss)
    {
        return new SimpleProfitAndLoss(inSimpleProfitAndLoss);
    }
}
