//
// this file is automatically generated
//
package org.marketcetera.strategy;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.security.NoSuchAlgorithmException;
import java.util.Optional;

import javax.annotation.PostConstruct;

import org.apache.commons.io.FileUtils;
import org.apache.commons.lang.Validate;
import org.marketcetera.core.PlatformServices;
import org.marketcetera.core.Preserve;
import org.marketcetera.rpc.base.BaseRpc;
import org.marketcetera.rpc.server.AbstractRpcService;
import org.marketcetera.strategy.StrategyRpc.FileUploadResponse;
import org.marketcetera.util.log.SLF4JLoggerProxy;
import org.springframework.boot.autoconfigure.AutoConfiguration;

import com.google.protobuf.ByteString;

import io.grpc.stub.StreamObserver;

/* $License$ */

/**
 * Provides an RPC Server for StrategyRpc services.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@Preserve
@AutoConfiguration
public class StrategyRpcServer<SessionClazz>
        extends AbstractRpcService<SessionClazz,StrategyRpcServiceGrpc.StrategyRpcServiceImplBase>
{
    /* (non-Javadoc)
    * @see AbstractRpcService#getServiceDescription()
    */
    @Override
    protected String getServiceDescription()
    {
        return description;
    }
    /* (non-Javadoc)
    * @see AbstractRpcService#getService()
    */
    @Override
    protected StrategyRpcServiceGrpc.StrategyRpcServiceImplBase getService()
    {
        return service;
    }
    /**
     * Validate and start the object.
     */
    @PostConstruct
    public void start()
            throws Exception
    {
        service = new Service();
        super.start();
    }
    /**
     * Write to the appropriate output file with the given upload metadata or file chunk.
     * 
     * @param inStrategyPath a <code>Path</code> value 
     * @return an <code>OutputStream</code> value
     * @throws IOException if an error occurs creating the file
     */
    private OutputStream getOutstreamFromFilePath(Path inStrategyPath)
            throws IOException
    {
        return Files.newOutputStream(inStrategyPath,
                                     StandardOpenOption.CREATE,
                                     StandardOpenOption.APPEND);
    }
    /**
     * Writes the given file chunk to the given file.
     *
     * @param inWriter an <code>OutputStream</code> value
     * @param inContent a <cod>ByteString</code> value
     * @throws IOException if an error occurs writing to the file
     */
    private void writeFile(OutputStream inWriter,
                           ByteString inContent)
            throws IOException
    {
        inWriter.write(inContent.toByteArray());
        inWriter.flush();
    }
    /**
     * Closes the given file writer.
     *
     * @param inWriter an <code>OutputStream</code> value
     * @throws IOException if an error occurs closing the file
     */
    private void closeFile(OutputStream inWriter)
            throws IOException
    {
        inWriter.close();
    }
    private void verifyAndMoveFile(Path inStrategyFile,
                                   String inNonce,
                                   String inName)
            throws NoSuchAlgorithmException, IOException
    {
        SLF4JLoggerProxy.debug(this,
                               "Verifying the uploaded strategy with the name '{}'",
                               inName);
        // find the incoming upload
        Optional<? extends StrategyInstance> strategyInstanceOption = strategyService.findByName(inName);
        Validate.isTrue(strategyInstanceOption.isPresent(),
                        "No strategy instance with name '" + inName + "' found");
        StrategyInstance strategyInstance = strategyInstanceOption.get();
        Validate.isTrue(inNonce.equals(strategyInstance.getNonce()),
                        "Strategy upload nonce does not match");
        String hash = PlatformServices.getFileChecksum(inStrategyFile.toFile());
        Validate.isTrue(hash.equals(strategyInstance.getHash()),
                        "Strategy upload hash does not match");
        Path strategyInstanceDirectory = strategyService.getIncomingStrategyDirectory();
        Path strategyFileTarget = strategyInstanceDirectory.resolve(inStrategyFile.getFileName());
        SLF4JLoggerProxy.debug(this,
                               "Verified the uploaded strategy with the name '{}', moving to strategy directory {}",
                               inName,
                               strategyFileTarget);
        FileUtils.moveFile(inStrategyFile.toFile(),
                           strategyFileTarget.toFile());
    }
    /**
     * StrategyRpc Service implementation.
     *
     * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
     * @version $Id$
     * @since $Release$
     */
    private class Service
            extends org.marketcetera.strategy.StrategyRpcServiceGrpc.StrategyRpcServiceImplBase
    {
        /* (non-Javadoc)
         * @see org.marketcetera.strategy.StrategyRpcServiceGrpc.StrategyRpcServiceImplBase#login(BaseRpc.LoginRequest, StreamObserver)
         */
        @Override
        public void login(BaseRpc.LoginRequest inRequest,StreamObserver<BaseRpc.LoginResponse> inResponseObserver)
        {
            StrategyRpcServer.this.doLogin(inRequest,inResponseObserver);
        }
        /* (non-Javadoc)
         * @see org.marketcetera.strategy.StrategyRpcServiceGrpc.StrategyRpcServiceImplBase#logout(BaseRpc.LogoutRequest, StreamObserver)
         */
        @Override
        public void logout(BaseRpc.LogoutRequest inRequest,StreamObserver<BaseRpc.LogoutResponse> inResponseObserver)
        {
            StrategyRpcServer.this.doLogout(inRequest,inResponseObserver);
        }
        /* (non-Javadoc)
         * @see org.marketcetera.strategy.StrategyRpcServiceGrpc.StrategyRpcServiceImplBase#heartbeat(BaseRpc.HeartbeatRequest, StreamObserver)
         */
        @Override
        public void heartbeat(BaseRpc.HeartbeatRequest inRequest,StreamObserver<BaseRpc.HeartbeatResponse> inResponseObserver)
        {
            StrategyRpcServer.this.doHeartbeat(inRequest,inResponseObserver);
        }
        /* (non-Javadoc)
         * @see org.marketcetera.strategy.StrategyRpcServiceGrpc.StrategyRpcServiceImplBase#getStrategyInstances(org.marketcetera.strategy.StrategyRpc.ReadStrategyInstancesRequest ,StreamObserver)
         */
        @Override
        public void getStrategyInstances(org.marketcetera.strategy.StrategyRpc.ReadStrategyInstancesRequest inReadStrategyInstancesRequest,StreamObserver<org.marketcetera.strategy.StrategyRpc.ReadStrategyInstancesResponse> inResponseObserver)
        {
            try {
                org.marketcetera.util.log.SLF4JLoggerProxy.trace(StrategyRpcServer.this,"Received {}",inReadStrategyInstancesRequest);
                org.marketcetera.util.ws.stateful.SessionHolder<SessionClazz> sessionHolder = validateAndReturnSession(inReadStrategyInstancesRequest.getSessionId());
                authzService.authorize(sessionHolder.getUser(),StrategyPermissions.ReadStrategyAction.name());
                authzService.authorize(sessionHolder.getUser(),StrategyPermissions.LoadStrategyAction.name());
                authzService.authorize(sessionHolder.getUser(),StrategyPermissions.UnloadStrategyAction.name());
                authzService.authorize(sessionHolder.getUser(),StrategyPermissions.StartStrategyAction.name());
                authzService.authorize(sessionHolder.getUser(),StrategyPermissions.StopStrategyAction.name());
                org.marketcetera.strategy.StrategyRpc.ReadStrategyInstancesResponse.Builder responseBuilder = org.marketcetera.strategy.StrategyRpc.ReadStrategyInstancesResponse.newBuilder();
                java.util.Collection<? extends org.marketcetera.strategy.StrategyInstance> serviceData = strategyService.getStrategyInstances(sessionHolder.getUser());
                serviceData.forEach(strategyInstance -> StrategyRpcUtil.getRpcStrategyInstance(strategyInstance).ifPresent(rpcStrategyInstance -> responseBuilder.addStrategyInstances(rpcStrategyInstance)));
                org.marketcetera.strategy.StrategyRpc.ReadStrategyInstancesResponse response = responseBuilder.build();
                org.marketcetera.util.log.SLF4JLoggerProxy.trace(StrategyRpcServer.this,"Responding {}",response);
                inResponseObserver.onNext(response);
                inResponseObserver.onCompleted();
            } catch (Exception e) {
                handleError(e,inResponseObserver);
            }
        }
        /* (non-Javadoc)
         * @see org.marketcetera.strategy.StrategyRpcServiceGrpc.StrategyRpcServiceImplBase#findByName(org.marketcetera.strategy.StrategyRpc.FindStrategyInstanceByNameRequest ,io.grpc.stub.StreamObserver)
         */
        @Override
        public void findByName(org.marketcetera.strategy.StrategyRpc.FindStrategyInstanceByNameRequest inFindStrategyInstanceByNameRequest,io.grpc.stub.StreamObserver<org.marketcetera.strategy.StrategyRpc.FindStrategyInstanceByNameResponse> inResponseObserver)
        {
            try {
                org.marketcetera.util.log.SLF4JLoggerProxy.trace(StrategyRpcServer.this,"Received findByNameRequest for {}",inFindStrategyInstanceByNameRequest);
                org.marketcetera.util.ws.stateful.SessionHolder<SessionClazz> sessionHolder = validateAndReturnSession(inFindStrategyInstanceByNameRequest.getSessionId());
                authzService.authorize(sessionHolder.getUser(),StrategyPermissions.ReadStrategyAction.name());
                org.marketcetera.strategy.StrategyRpc.FindStrategyInstanceByNameResponse.Builder responseBuilder = org.marketcetera.strategy.StrategyRpc.FindStrategyInstanceByNameResponse.newBuilder();
                String name = inFindStrategyInstanceByNameRequest.getName();
                java.util.Optional<? extends org.marketcetera.strategy.StrategyInstance> serviceData = strategyService.findByName(name);
                serviceData.ifPresent(strategyInstance -> StrategyRpcUtil.getRpcStrategyInstance(strategyInstance).ifPresent(rpcStrategyInstance -> responseBuilder.setStrategyInstance(rpcStrategyInstance)));
                org.marketcetera.strategy.StrategyRpc.FindStrategyInstanceByNameResponse response = responseBuilder.build();
                org.marketcetera.util.log.SLF4JLoggerProxy.trace(StrategyRpcServer.this,"Responding {}",response);
                inResponseObserver.onNext(response);
                inResponseObserver.onCompleted();
            } catch (Exception e) {
                handleError(e,inResponseObserver);
            }
        }
        /* (non-Javadoc)
         * @see org.marketcetera.strategy.StrategyRpcServiceGrpc.StrategyRpcServiceImplBase#loadStrategyInstance(org.marketcetera.strategy.StrategyRpc.LoadStrategyInstanceRequest ,StreamObserver)
         */
        @Override
        public void loadStrategyInstance(org.marketcetera.strategy.StrategyRpc.LoadStrategyInstanceRequest inLoadStrategyInstanceRequest,StreamObserver<org.marketcetera.strategy.StrategyRpc.LoadStrategyInstanceResponse> inResponseObserver)
        {
            try {
                org.marketcetera.util.log.SLF4JLoggerProxy.trace(StrategyRpcServer.this,"Received {}",inLoadStrategyInstanceRequest);
                org.marketcetera.util.ws.stateful.SessionHolder<SessionClazz> sessionHolder = validateAndReturnSession(inLoadStrategyInstanceRequest.getSessionId());
                authzService.authorize(sessionHolder.getUser(),StrategyPermissions.LoadStrategyAction.name());
                org.marketcetera.strategy.StrategyRpc.LoadStrategyInstanceResponse.Builder responseBuilder = org.marketcetera.strategy.StrategyRpc.LoadStrategyInstanceResponse.newBuilder();
                org.marketcetera.strategy.StrategyInstance strategyInstance = StrategyRpcUtil.getStrategyInstance(inLoadStrategyInstanceRequest.getStrategyInstance(),strategyInstanceFactory,userFactory).orElse(null);
                org.marketcetera.strategy.StrategyStatus serviceData = strategyService.loadStrategyInstance(strategyInstance);
                StrategyRpcUtil.getRpcStrategyStatus(serviceData).ifPresent(rpcStatus -> responseBuilder.setStatus(rpcStatus));
                org.marketcetera.strategy.StrategyRpc.LoadStrategyInstanceResponse response = responseBuilder.build();
                org.marketcetera.util.log.SLF4JLoggerProxy.trace(StrategyRpcServer.this,"Responding {}",response);
                inResponseObserver.onNext(response);
                inResponseObserver.onCompleted();
            } catch (Exception e) {
                handleError(e,inResponseObserver);
            }
        }
        /* (non-Javadoc)
         * @see org.marketcetera.strategy.StrategyRpcServiceGrpc.StrategyRpcServiceImplBase#unloadStrategyInstance(org.marketcetera.strategy.StrategyRpc.UnloadStrategyInstanceRequest ,io.grpc.stub.StreamObserver)
         */
        @Override
        public void unloadStrategyInstance(org.marketcetera.strategy.StrategyRpc.UnloadStrategyInstanceRequest inUnloadStrategyInstanceRequest,io.grpc.stub.StreamObserver<org.marketcetera.strategy.StrategyRpc.UnloadStrategyInstanceResponse> inResponseObserver)
        {
            try {
                org.marketcetera.util.log.SLF4JLoggerProxy.trace(StrategyRpcServer.this,"Received {}",inUnloadStrategyInstanceRequest);
                org.marketcetera.util.ws.stateful.SessionHolder<SessionClazz> sessionHolder = validateAndReturnSession(inUnloadStrategyInstanceRequest.getSessionId());
                authzService.authorize(sessionHolder.getUser(),StrategyPermissions.UnloadStrategyAction.name());
                org.marketcetera.strategy.StrategyRpc.UnloadStrategyInstanceResponse.Builder responseBuilder = org.marketcetera.strategy.StrategyRpc.UnloadStrategyInstanceResponse.newBuilder();
                String strategyInstanceName = inUnloadStrategyInstanceRequest.getName();
                strategyService.unloadStrategyInstance(strategyInstanceName);
                org.marketcetera.strategy.StrategyRpc.UnloadStrategyInstanceResponse response = responseBuilder.build();
                org.marketcetera.util.log.SLF4JLoggerProxy.trace(StrategyRpcServer.this,"Responding {}",response);
                inResponseObserver.onNext(response);
                inResponseObserver.onCompleted();
            } catch (Exception e) {
                handleError(e,inResponseObserver);
            }
        }
        /* (non-Javadoc)
         * @see org.marketcetera.strategy.StrategyRpcServiceGrpc.StrategyRpcServiceImplBase#uploadFile(StreamObserver)
         */
        @Override
        public StreamObserver<StrategyRpc.FileUploadRequest> uploadFile(StreamObserver<StrategyRpc.FileUploadResponse> inResponseObserver)
        {
            return new StreamObserver<StrategyRpc.FileUploadRequest>() {
                @Override
                public void onNext(StrategyRpc.FileUploadRequest inFileUploadRequest)
                {
                    try {
                        switch(inFileUploadRequest.getRequestCase()) {
                            case FILE:
                                writeFile(writer,
                                          inFileUploadRequest.getFile().getContent());
                                break;
                            case METADATA:
                                uploadNonce = inFileUploadRequest.getMetadata().getNonce();
                                instanceName = inFileUploadRequest.getMetadata().getName();
                                // determined to be JAR files right now, might be nice to include file type in the upload request
                                String fileName = inFileUploadRequest.getMetadata().getNonce() + ".jar";
                                strategyPath = strategyService.getTemporaryStrategyDirectory().resolve(fileName);
                                SLF4JLoggerProxy.warn(StrategyRpcServer.this,
                                                      "COCO: writing incoming strategy to {}",
                                                      strategyPath);
                                writer = getOutstreamFromFilePath(strategyPath);
                                break;
                            case REQUEST_NOT_SET:
                            default:
                                throw new UnsupportedOperationException("Request case not set in file upload request");
                        }
                    } catch (IOException e) {
                        SLF4JLoggerProxy.error(StrategyRpcServer.this,
                                               e);
                        this.onError(e);
                    }
                }
                @Override
                public void onError(Throwable throwable)
                {
                    status = StrategyTypesRpc.FileUploadStatus.FAILED;
                    this.onCompleted();
                }
                @Override
                public void onCompleted()
                {
                    try {
                        closeFile(writer);
                        verifyAndMoveFile(strategyPath,
                                          uploadNonce,
                                          instanceName);
                        status = StrategyTypesRpc.FileUploadStatus.SUCCESS;
                    } catch (Exception e) {
                        SLF4JLoggerProxy.warn(StrategyRpcServer.this,
                                              e);
                        status = StrategyTypesRpc.FileUploadStatus.FAILED;
                    }
                    FileUploadResponse response = FileUploadResponse.newBuilder().setStatus(status).build();
                    inResponseObserver.onNext(response);
                    inResponseObserver.onCompleted();
                }
                private String instanceName;
                private String uploadNonce;
                private Path strategyPath;
                private OutputStream writer;
                private StrategyTypesRpc.FileUploadStatus status = StrategyTypesRpc.FileUploadStatus.IN_PROGRESS;
            };
        }
    }
    /**
     * Creates new StrategyInstance objects
     */
    @org.springframework.beans.factory.annotation.Autowired
    private org.marketcetera.strategy.StrategyInstanceFactory strategyInstanceFactory;
    /**
     * Creates new User objects
     */
    @org.springframework.beans.factory.annotation.Autowired
    private org.marketcetera.admin.UserFactory userFactory;
    /**
     * provides services for Strategy
     */
    @org.springframework.beans.factory.annotation.Autowired
    private StrategyService strategyService;
    /**
     * provides access to authorization services
     */
    @org.springframework.beans.factory.annotation.Autowired
    private org.marketcetera.admin.service.AuthorizationService authzService;
    /**
     * provides the RPC service
     */
    private Service service;
    /**
     * description of this service
     */
    private final static String description = "Strategy RPC Service";
}
