//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

/* $License$ */

/**
 * Describes the current position of a given instrument owned by a given user.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface CurrentPosition
        extends org.marketcetera.trade.HasInstrument,org.marketcetera.admin.HasUser
{
    /**
     * Get the position value.
     *
     * @return a <code>java.math.BigDecimal</code> value
     */
    java.math.BigDecimal getPosition();
    /**
     * Set the position value.
     *
     * @param inPosition a <code>java.math.BigDecimal</code> value
     */
    void setPosition(java.math.BigDecimal inPosition);
    /**
     * Get the weightedAverageCost value.
     *
     * @return a <code>java.math.BigDecimal</code> value
     */
    java.math.BigDecimal getWeightedAverageCost();
    /**
     * Set the weightedAverageCost value.
     *
     * @param inWeightedAverageCost a <code>java.math.BigDecimal</code> value
     */
    void setWeightedAverageCost(java.math.BigDecimal inWeightedAverageCost);
    /**
     * Get the realizedGain value.
     *
     * @return a <code>java.math.BigDecimal</code> value
     */
    java.math.BigDecimal getRealizedGain();
    /**
     * Set the realizedGain value.
     *
     * @param inRealizedGain a <code>java.math.BigDecimal</code> value
     */
    void setRealizedGain(java.math.BigDecimal inRealizedGain);
    /**
     * Get the unrealizedGain value.
     *
     * @return a <code>java.math.BigDecimal</code> value
     */
    java.math.BigDecimal getUnrealizedGain();
    /**
     * Set the unrealizedGain value.
     *
     * @param inUnrealizedGain a <code>java.math.BigDecimal</code> value
     */
    void setUnrealizedGain(java.math.BigDecimal inUnrealizedGain);
}
