//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

/* $License$ */

/**
 * Provides a user-centric view of a {@link Trade}.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface HasUserTrade
{
    /**
     * Get the usertrade value.
     *
     * @return a <code>UserTrade</code> value
     */
    UserTrade getUserTrade();
    /**
     * Set the usertrade value.
     *
     * @param inUserTrade a <code>UserTrade</code> value
     */
    void setUserTrade(UserTrade inUserTrade);
}
