//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

/* $License$ */

/**
 * Creates new {@link Lot} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface LotFactory
        extends org.marketcetera.core.Factory<Lot>
{
    /**
     * Create a new <code>Lot</code> instance.
     *
     * @return a <code>Lot</code> value
     */
    @Override
    Lot create();
    /**
     * Create a new <code>Lot</code> instance from the given object.
     *
     * @param inLot a <code>Lot</code> value
     * @return a <code>Lot</code> value
     */
    @Override
    Lot create(Lot inLot);
}
