//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

/* $License$ */

/**
 * Creates new {@link Position} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface PositionFactory
        extends org.marketcetera.core.Factory<Position>
{
    /**
     * Create a new <code>Position</code> instance.
     *
     * @return a <code>Position</code> value
     */
    @Override
    Position create();
    /**
     * Create a new <code>Position</code> instance from the given object.
     *
     * @param inPosition a <code>Position</code> value
     * @return a <code>Position</code> value
     */
    @Override
    Position create(Position inPosition);
}
