//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

import org.marketcetera.core.Preserve;
import org.marketcetera.persist.PageRequest;
import org.marketcetera.trade.Instrument;
import org.marketcetera.trade.UserID;

/* $License$ */

/**
 * Provides a client interface for TradePnlRpc services.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@Preserve
public interface TradePnlClient
        extends org.marketcetera.core.BaseClient
{
    /**
     * Requests positions for a user.
     *
     * @param inUserID a <code>UserID</code> value
     * @param inPageRequest a <code>PageRequest</code> value
     * @return a <code>CurrentPosition</code> value
     */
    CurrentPosition getCurrentPositions(UserID inUserID,
                                        PageRequest inPageRequest);
    /**
     * Requests profit and loss for a user and an instrument.
     *
     * @param inUserID a <code>UserID</code> value
     * @param inInstrument a <code>Instrument</code> value
     * @param inPageRequest a <code>PageRequest</code> value
     * @return a <code>ProfitAndLoss</code> value
     */
    ProfitAndLoss getProfitAndLoss(UserID inUserID,
                                   Instrument inInstrument,
                                   PageRequest inPageRequest);
}
