//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

/* $License$ */

/**
 * Provides parameters necessary to connect to a {@link TradePnlClient}.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface TradePnlClientParameters
        extends org.marketcetera.core.ClientParameters
{
}
