//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

import org.marketcetera.core.Factory;
import org.marketcetera.core.Preserve;

/* $License$ */

/**
 * Creates new {@link UserTrade} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@Preserve
public interface UserTradeFactory
        extends Factory<UserTrade>
{
    /**
     * Create a new <code>UserTrade</code> instance.
     *
     * @return a <code>UserTrade</code> value
     */
    @Override
    UserTrade create();
    /**
     * Create a new <code>UserTrade</code> instance from the given object.
     *
     * @param inUserTrade a <code>UserTrade</code> value
     * @return a <code>UserTrade</code> value
     */
    @Override
    UserTrade create(UserTrade inUserTrade);
}
