<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.marketcetera</groupId>
    <artifactId>trade-parent</artifactId>
    <version>4.1.1</version>
  </parent>
  <groupId>org.marketcetera</groupId>
  <artifactId>trade-rpc-proto</artifactId>
  <version>4.1.1</version>
  <name>Trade RPC Proto</name>
  <description>Trade RPC Proto Buffer Definitions</description>
  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>rpc-core-proto</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>cluster-rpc-proto</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>fix-rpc-proto</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>admin-rpc-proto</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-stub</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-protobuf</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-core</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
    </dependency>
  </dependencies>
  <build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.7.1</version>
      </extension>
    </extensions>
    <plugins>
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>0.6.1</version>
        <configuration>
          <protocArtifact>com.google.protobuf:protoc:3.6.1:exe:${os.detected.classifier}</protocArtifact>
          <pluginId>grpc-java</pluginId>
          <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.0.0:exe:${os.detected.classifier}</pluginArtifact>
          <protoSourceRoot>${project.basedir}/src/main/proto</protoSourceRoot>
          <additionalProtoPathElements>
            <additionalProtoPathElement>${project.basedir}/../../rpc-core-proto/src/main/proto</additionalProtoPathElement>
            <additionalProtoPathElement>${project.basedir}/../../cluster/cluster-rpc-proto/src/main/proto</additionalProtoPathElement>
            <additionalProtoPathElement>${project.basedir}/../../fix/fix-rpc-proto/src/main/proto</additionalProtoPathElement>
            <additionalProtoPathElement>${project.basedir}/../../admin/admin-rpc-proto/src/main/proto</additionalProtoPathElement>
          </additionalProtoPathElements>
          <attachProtoSources>true</attachProtoSources>
          <checkStaleness>true</checkStaleness>
        </configuration>
        <executions>
          <execution>
            <id>compile-protos</id>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
            </goals>
          </execution>
          <execution>
            <id>compile-test-protos</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>test-compile</goal>
              <goal>test-compile-custom</goal>
            </goals>
            <configuration>
              <protoSourceRoot>${project.basedir}/src/test/proto</protoSourceRoot>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.eclipse.m2e</groupId>
        <artifactId>lifecycle-mapping</artifactId>
        <version>1.0.0</version>
        <configuration>
          <lifecycleMappingMetadata>
            <pluginExecutions>
              <pluginExecution>
                <pluginExecutionFilter>
                  <groupId>org.xolstice.maven.plugins</groupId>
                  <artifactId>protobuf-maven-plugin</artifactId>
                  <versionRange>[0,)</versionRange>
                  <goals>
                    <goal>compile</goal>
                    <goal>compile-custom</goal>
                    <goal>test-compile</goal>
                    <goal>test-compile-custom</goal>
                  </goals>
                </pluginExecutionFilter>
                <action>
                  <execute />
                </action>
              </pluginExecution>
            </pluginExecutions>
          </lifecycleMappingMetadata>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/generated-sources/protobuf/java</source>
                <source>${project.build.directory}/generated-sources/protobuf/grpc-java</source>
              </sources>
            </configuration>
          </execution>
          <execution>
            <id>add-test-source</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>${project.build.directory}/generated-test-sources/protobuf/java</source>
                <source>${project.build.directory}/generated-test-sources/protobuf/grpc-java</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>ide-build</id>
      <properties>
        <skipTests>true</skipTests>
      </properties>
      <build>
        <directory>${project.basedir}/target-ide</directory>
      </build>
    </profile>
  </profiles>
</project>
