//
// this file is automatically generated
//
package org.marketcetera.eventbus.data.event;

/* $License$ */

/**
 * Creates new {@link DataEvent} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface DataEventFactory
        extends org.marketcetera.core.Factory<DataEvent>
{
    /**
     * Create a new <code>DataEvent</code> instance.
     *
     * @return a <code>DataEvent</code> value
     */
    @Override
    DataEvent create();
    /**
     * Create a new <code>DataEvent</code> instance from the given object.
     *
     * @param inObject a <code>DataEvent</code> value
     * @return a <code>DataEvent</code> value
     */
    @Override
    DataEvent create(DataEvent inDataEvent);
}
