//
// this file is automatically generated
//
package org.marketcetera.eventbus.data.event;

/* $License$ */

/**
 * Provides parameters necessary to connect to a {@link DataEventClient}.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface DataEventClientParameters
        extends org.marketcetera.core.ClientParameters
{
}
