//
// this file is automatically generated
//
package org.marketcetera.eventbus.data;

/* $License$ */

/**
 * Creates {@link DataEventClient} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface DataEventClientFactory<ParameterClazz>
{
    /**
     * Create a new {@link DataEventClient} instance.
     *
     * @param inParameterClazz a <code>ParameterClazz</code> value
     * @return a <code>DataEventClient</code> value
     */
    DataEventClient create(ParameterClazz inParameterClazz);
}
