//
// this file is automatically generated
//
package org.marketcetera.eventbus.data;

/* $License$ */

/**
 * Provides permissions for services.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public enum DataEventPermissions
{
}
