//
// this file is automatically generated
//
package org.marketcetera.eventbus.data;

/* $License$ */

/**
 * Type of the change.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public enum DataEventChangeType
{
    /**
     * data added
     */
    ADD,
    /**
     * data changed
     */
    CHANGE,
    /**
     * data deleted
     */
    DELETE,
}
