#!/bin/sh
set -e
### BEGIN INIT INFO
# Provides: dare
# Required-Start: $local_fs $remote_fs $network $time
# Required-Stop: $local_fs $remote_fs $network $time
# Should-Start: $syslog
# Should-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Marketcetera Deploy Anywhere Routing Engine
### END INIT INFO
# INIT Script
######################################

# Define some variables
# Name of app
APP=dare
# Name of the user to run as
USER=marketcetera
# Location of application's bin directory
BASE=/opt/Marketcetera
dare_HOME=${BASE}/dare

case "$1" in
# Start command
start)
echo "Starting $APP"
/bin/su - $USER -c "${dare_HOME}/bin/dare.sh"
;;
# Stop command
stop)
echo "Stopping $APP"
/bin/su - $USER -c "kill `cat ${dare_HOME}/dare.pid` && rm ${dare_HOME}/dare.pid"
echo "$APP stopped successfully"
;;
# Restart command
restart)
$0 stop
sleep 5
$0 start
;;
*)
echo "Usage: /etc/init.d/$APP {start|restart|stop}"
exit 1
;;
esac

exit 0
