INSERT INTO currencies (alpha_code, numeric_code, description, obsolete, created_on) VALUES
('AED',784,'United Arab Emirates dirham', 'N', NOW() ),
('AFN',971,'Afghani', 'N', NOW() ),
('ALL',008,'Lek', 'N', NOW() ),
('AMD',051,'Armenian Dram', 'N', NOW() ),
('ANG',532,'Netherlands Antillian Guilder', 'N', NOW() ),
('AOA',973,'Kwanza', 'N', NOW() ),
('ARS',032,'Argentine Peso', 'N', NOW() ),
('AUD',036,'Australian Dollar', 'N', NOW() ),
('AWG',533,'Aruban Guilder', 'N', NOW() ),
('AZN',944,'Azerbaijanian Manat', 'N', NOW() ),
('BAM',977,'Convertible Marks', 'N', NOW() ),
('BBD',052,'Barbados Dollar', 'N', NOW() ),
('BDT',050,'Taka', 'N', NOW() ),
('BGN',975,'Bulgarian Lev', 'N', NOW() ),
('BHD',048,'Bahraini Dinar', 'N', NOW() ),
('BIF',108,'Burundian Franc', 'N', NOW() ),
('BMD',060,'Bermudian Dollar (customarily known as Bermuda Dollar)', 'N', NOW() ),
('BND',096,'Brunei Dollar', 'N', NOW() ),
('BOB',068,'Boliviano', 'N', NOW() ),
('BOV',984,'Bolivian Mvdol (Funds code)', 'N', NOW() ),
('BRL',986,'Brazilian Real', 'N', NOW() ),
('BSD',044,'Bahamian Dollar', 'N', NOW() ),
('BTN',064,'Ngultrum', 'N', NOW() ),
('BWP',072,'Pula', 'N', NOW() ),
('BYR',974,'Belarussian Ruble', 'N', NOW() ),
('BZD',084,'Belize Dollar', 'N', NOW() ),
('CAD',124,'Canadian Dollar', 'N', NOW() ),
('CDF',976,'Franc Congolais', 'N', NOW() ),
('CHE',947,'WIR Euro', 'N', NOW() ),
('CHF',756,'Swiss Franc', 'N', NOW() ),
('CHW',948,'WIR Franc', 'N', NOW() ),
('CLF',990,'Unidades de formento (Funds code)', 'N', NOW() ),
('CLP',152,'Chilean Peso', 'N', NOW() ),
('CNY',156,'Yuan Renminbi', 'N', NOW() ),
('COP',170,'Colombian Peso', 'N', NOW() ),
('COU',970,'Unidad de Valor Real', 'N', NOW() ),
('CRC',188,'Costa Rican Colon', 'N', NOW() ),
('CSD',891,'Serbian Dinar', 'N', NOW() ),
('CUP',192,'Cuban Peso', 'N', NOW() ),
('CVE',132,'Cape Verde Escudo', 'N', NOW() ),
('CYP',196,'Cyprus Pound', 'N', NOW() ),
('CZK',203,'Czech Koruna', 'N', NOW() ),
('DJF',262,'Djibouti Franc', 'N', NOW() ),
('DKK',208,'Danish Krone', 'N', NOW() ),
('DOP',214,'Dominican Peso', 'N', NOW() ),
('DZD',012,'Algerian Dinar', 'N', NOW() ),
('EEK',233,'Kroon', 'N', NOW() ),
('EGP',818,'Egyptian Pound', 'N', NOW() ),
('ERN',232,'Nakfa', 'N', NOW() ),
('ETB',230,'Ethiopian Birr', 'N', NOW() ),
('EUR',978,'Euro', 'N', NOW() ),
('FJD',242,'Fiji Dollar', 'N', NOW() ),
('FKP',238,'Falkland Islands Pound', 'N', NOW() ),
('GBP',826,'Pound Sterling', 'N', NOW() ),
('GEL',981,'Lari', 'N', NOW() ),
('GHC',288,'Cedi', 'N', NOW() ),
('GIP',292,'Gibraltar pound', 'N', NOW() ),
('GMD',270,'Dalasi', 'N', NOW() ),
('GNF',324,'Guinea Franc', 'N', NOW() ),
('GTQ',320,'Quetzal', 'N', NOW() ),
('GYD',328,'Guyana Dollar', 'N', NOW() ),
('HKD',344,'Hong Kong Dollar', 'N', NOW() ),
('HNL',340,'Lempira', 'N', NOW() ),
('HRK',191,'Croatian Kuna', 'N', NOW() ),
('HTG',332,'Haiti Gourde', 'N', NOW() ),
('HUF',348,'Forint', 'N', NOW() ),
('IDR',360,'Rupiah', 'N', NOW() ),
('ILS',376,'New Israeli Shekel', 'N', NOW() ),
('INR',356,'Indian Rupee', 'N', NOW() ),
('IQD',368,'Iraqi Dinar', 'N', NOW() ),
('IRR',364,'Iranian Rial', 'N', NOW() ),
('ISK',352,'Iceland Krona', 'N', NOW() ),
('JMD',388,'Jamaican Dollar', 'N', NOW() ),
('JOD',400,'Jordanian Dinar', 'N', NOW() ),
('JPY',392,'Japanese yen', 'N', NOW() ),
('KES',404,'Kenyan Shilling', 'N', NOW() ),
('KGS',417,'Som', 'N', NOW() ),
('KHR',116,'Riel', 'N', NOW() ),
('KMF',174,'Comoro Franc', 'N', NOW() ),
('KPW',408,'North Korean Won', 'N', NOW() ),
('KRW',410,'Won', 'N', NOW() ),
('KWD',414,'Kuwaiti Dinar', 'N', NOW() ),
('KYD',136,'Cayman Islands Dollar', 'N', NOW() ),
('KZT',398,'Tenge', 'N', NOW() ),
('LAK',418,'Kip', 'N', NOW() ),
('LBP',422,'Lebanese Pound', 'N', NOW() ),
('LKR',144,'Sri Lanka Rupee', 'N', NOW() ),
('LRD',430,'Liberian Dollar', 'N', NOW() ),
('LSL',426,'Loti', 'N', NOW() ),
('LTL',440,'Lithuanian Litas', 'N', NOW() ),
('LVL',428,'Latvian Lats', 'N', NOW() ),
('LYD',434,'Libyan Dinar', 'N', NOW() ),
('MAD',504,'Moroccan Dirham', 'N', NOW() ),
('MDL',498,'Moldovan Leu', 'N', NOW() ),
('MGA',969,'Malagasy Ariary', 'N', NOW() ),
('MKD',807,'Denar', 'N', NOW() ),
('MMK',104,'Kyat', 'N', NOW() ),
('MNT',496,'Tugrik', 'N', NOW() ),
('MOP',446,'Pataca', 'N', NOW() ),
('MRO',478,'Ouguiya', 'N', NOW() ),
('MTL',470,'Maltese Lira', 'N', NOW() ),
('MUR',480,'Mauritius Rupee', 'N', NOW() ),
('MVR',462,'Rufiyaa', 'N', NOW() ),
('MWK',454,'Kwacha', 'N', NOW() ),
('MXN',484,'Mexican Peso', 'N', NOW() ),
('MXV',979,'Mexican Unidad de Inversion (UDI) (Funds code) (Mexico)', 'N', NOW() ),
('MYR',458,'Malaysian Ringgit', 'N', NOW() ),
('MZN',943,'Metical', 'N', NOW() ),
('NAD',516,'Namibian Dollar', 'N', NOW() ),
('NGN',566,'Naira', 'N', NOW() ),
('NIO',558,'Cordoba Oro', 'N', NOW() ),
('NOK',578,'Norwegian Krone', 'N', NOW() ),
('NPR',524,'Nepalese Rupee', 'N', NOW() ),
('NZD',554,'New Zealand Dollar', 'N', NOW() ),
('OMR',512,'Rial Omani', 'N', NOW() ),
('PAB',590,'Balboa', 'N', NOW() ),
('PEN',604,'Nuevo Sol', 'N', NOW() ),
('PGK',598,'Kina', 'N', NOW() ),
('PHP',608,'Philippine Peso', 'N', NOW() ),
('PKR',586,'Pakistan Rupee', 'N', NOW() ),
('PLN',985,'Zloty', 'N', NOW() ),
('PYG',600,'Guarani', 'N', NOW() ),
('QAR',634,'Qatari Rial', 'N', NOW() ),
('ROL',642,'Old Romanian Leu', 'N', NOW() ),
('RON',946,'New Leu', 'N', NOW() ),
('RUB',643,'Russian Ruble', 'N', NOW() ),
('RWF',646,'Rwanda Franc', 'N', NOW() ),
('SAR',682,'Saudi Riyal', 'N', NOW() ),
('SBD',090,'Solomon Islands Dollar', 'N', NOW() ),
('SCR',690,'Seychelles Rupee', 'N', NOW() ),
('SDD',736,'Sudanese Dinar', 'N', NOW() ),
('SEK',752,'Swedish Krona', 'N', NOW() ),
('SGD',702,'Singapore Dollar', 'N', NOW() ),
('SHP',654,'Saint Helena Pound', 'N', NOW() ),
('SIT',705,'Tolar', 'N', NOW() ),
('SKK',703,'Slovak Koruna', 'N', NOW() ),
('SLL',694,'Leone', 'N', NOW() ),
('SOS',706,'Somali Shilling', 'N', NOW() ),
('SRD',968,'Surinam Dollar', 'N', NOW() ),
('STD',678,'Dobra', 'N', NOW() ),
('SYP',760,'Syrian Pound', 'N', NOW() ),
('SZL',748,'Lilangeni', 'N', NOW() ),
('THB',764,'Baht', 'N', NOW() ),
('TJS',972,'Somoni', 'N', NOW() ),
('TMM',795,'Manat', 'N', NOW() ),
('TND',788,'Tunisian Dinar', 'N', NOW() ),
('TOP',776,'Pa\'anga', 'N', NOW() ),
('TRY',949,'New Turkish Lira', 'N', NOW() ),
('TTD',780,'Trinidad and Tobago Dollar', 'N', NOW() ),
('TWD',901,'New Taiwan Dollar', 'N', NOW() ),
('TZS',834,'Tanzanian Shilling', 'N', NOW() ),
('UAH',980,'Hryvnia', 'N', NOW() ),
('UGX',800,'Uganda Shilling', 'N', NOW() ),
('USD',840,'US Dollar', 'N', NOW() ),
('USN',997,null, 'N', NOW() ),
('USS',998,null, 'N', NOW() ),
('UYU',858,'Peso Uruguayo', 'N', NOW() ),
('UZS',860,'Uzbekistan Som', 'N', NOW() ),
('VEB',862,'Venezuelan bolívar', 'N', NOW() ),
('VND',704,'Dong', 'N', NOW() ),
('VUV',548,'Vatu', 'N', NOW() ),
('WST',882,'Tala', 'N', NOW() ),
('XAF',950,'CFA Franc BEAC', 'N', NOW() ),
('XAG',961,'Silver (one Troy ounce)', 'N', NOW() ),
('XAU',959,'Gold (one Troy ounce)', 'N', NOW() ),
('XBA',955,'European Composite Unit (EURCO) (Bonds market unit)', 'N', NOW() ),
('XBB',956,'European Monetary Unit (E.M.U.-6) (Bonds market unit)', 'N', NOW() ),
('XBC',957,'European Unit of Account 9 (E.U.A.-9) (Bonds market unit)', 'N', NOW() ),
('XBD',958,'European Unit of Account 17 (E.U.A.-17) (Bonds market unit)', 'N', NOW() ),
('XCD',951,'East Caribbean Dollar', 'N', NOW() ),
('XDR',960,'Special Drawing Rights', 'N', NOW() ),
('XFO',null,'Gold-Franc (Special settlement currency)', 'N', NOW() ),
('XFU',null,'UIC Franc (Special settlement currency)', 'N', NOW() ),
('XOF',952,'CFA Franc BCEAO', 'N', NOW() ),
('XPD',964,'Palladium (one Troy ounce)', 'N', NOW() ),
('XPF',953,'CFP franc', 'N', NOW() ),
('XPT',962,'Platinum (one Troy ounce)', 'N', NOW() ),
('XTS',963,'Code reserved for testing purposes', 'N', NOW() ),
('XXX',999,'No currency', 'N', NOW() ),
('YER',886,'Yemeni Rial', 'N', NOW() ),
('ZAR',710,'Rand', 'N', NOW() ),
('ZMK',894,'Kwacha', 'N', NOW() ),
('ZWD',942,'Zimbabwe Dollar', 'N', NOW() )
;

INSERT INTO currencies (alpha_code, numeric_code, description, obsolete, created_on) VALUES
('ZWD',942,'Zimbabwe Dollar','Y', NOW() ),
('ADP',20,'Andorran Peseta','Y', NOW() ),
('ATS',40,'Austrian Schilling','Y', NOW() ),
('BEF',56,'Belgian Franc','Y', NOW() ),
('DEM',276,'Deutsche Mark','Y', NOW() ),
('ESP',724,'Spanish Peseta','Y', NOW() ),
('FIM',246,'Finnish Markka','Y', NOW() ),
('FRF',250,'French Franc','Y', NOW() ),
('GRD',300,'Greek Drachma','Y', NOW() ),
('IEP',372,'Irish Pound','Y', NOW() ),
('ITL',380,'Italian Lira','Y', NOW() ),
('LUF',442,'Luxembourg Franc','Y', NOW() ),
('NLG',528,'Netherlands Guilder','Y', NOW() ),
('PTE',620,'Portuguese Escudo','Y', NOW() ),
('XEU',954,'European Currency Unit','Y', NOW() ),
('ADF',null,'Andorran Franc','Y', NOW() ),
('AFA',4,'Afghani','Y', NOW() ),
('ALK',null,'Albanian old lek','Y', NOW() ),
('AON',24,'Angolan New Kwanza','Y', NOW() ),
('AOR',982,'Angolan Kwanza Readjustado','Y', NOW() ),
('ARP',null,'Peso Argentino','Y', NOW() ),
('ARY',null,'Argentine peso','Y', NOW() ),
('AZM',31,'Azerbaijani manat','Y', NOW() ),
('BEC',993,'Belgian Franc (convertible)','Y', NOW() ),
('BEL',992,'Belgian Franc (financial)','Y', NOW() ),
('BGJ',null,'Bulgarian lev A/52','Y', NOW() ),
('BGK',null,'Bulgarian lev A/62','Y', NOW() ),
('BGL',100,'Bulgarian lev A/99','Y', NOW() ),
('BOP',null,'Bolivian peso','Y', NOW() ),
('BRB',null,'Brazilian cruzeiro','Y', NOW() ),
('BRC',null,'Brazilian cruzado','Y', NOW() ),
('CNX',null,'Chinese People\'s Bank dollar','Y', NOW() ),
('CSJ',null,'Czechoslovak koruna A/53','Y', NOW() ),
('CSK',200,'Czechoslovak koruna','Y', NOW() ),
('DDM',278,'mark der DDR (East Germany)','Y', NOW() ),
('ECS',218,'Ecuador sucre','Y', NOW() ),
('ECV',983,'Ecuador Unidad de Valor Constante (Funds code) (discontinued)','Y', NOW() ),
('EQE',null,'Equatorial Guinean ekwele','Y', NOW() ),
('ESA',996,'Spanish peseta (account A)','Y', NOW() ),
('ESB',995,'Spanish peseta (account B)','Y', NOW() ),
('GNE',null,'Guinean syli','Y', NOW() ),
('GWP',624,'Guinea peso','Y', NOW() ),
('ILP',null,'Israeli pound','Y', NOW() ),
('ILR',null,'Israeli old shekel','Y', NOW() ),
('ISJ',null,'Icelandic old krona','Y', NOW() ),
('LAJ',null,'Lao kip - Pot Pol','Y', NOW() ),
('MAF',null,'Mali franc','Y', NOW() ),
('MGF',450,'Malagasy franc','Y', NOW() ),
('MKN',null,'Macedonian denar A/93','Y', NOW() ),
('MVQ',null,'Maldive rupee','Y', NOW() ),
('MXP',null,'Mexican peso','Y', NOW() ),
('MZM',508,'Metical','Y', NOW() ),
('PEH',null,'Peruvian sol','Y', NOW() ),
('PEI',null,'Peruvian inti','Y', NOW() ),
('PLZ',616,'Polish zloty A/94','Y', NOW() ),
('ROK',null,'Romanian leu A/52','Y', NOW() ),
('ROL',642,'Romanian leu A/05','Y', NOW() ),
('RUR',810,'Russian ruble','Y', NOW() ),
('SRG',740,'Suriname guilder','Y', NOW() ),
('SUR',null,'Soviet Union ruble','Y', NOW() ),
('SVC',222,'Salvadoran colón','Y', NOW() ),
('TJR',762,'','Y', NOW() ),
('TPE',626,'Timor escudo','Y', NOW() ),
('TRL',792,'Turkish lira A/05','Y', NOW() ),
('UAK',804,'Ukrainian karbovanets','Y', NOW() ),
('UGW',null,'Ugandan old shilling','Y', NOW() ),
('UYN',null,'Uruguay old peso','Y', NOW() ),
('VNC',null,'Vietnamese old dong','Y', NOW() ),
('YDD',720,'South Yemeni dinar','Y', NOW() ),
('YUD',null,'New Yugoslavian Dinar','Y', NOW() ),
('YUM',891,'Yugoslavian Dinar','Y', NOW() ),
('ZAL',991,'South African financial rand (Funds code) (discontinued)','Y', NOW() ),
('ZRN',180,'New Zaire','Y', NOW() ),
('ZRZ',null,'Zaire','Y', NOW() ),
('ZWC',null,'Zimbabwe Rhodesian dollar','Y', NOW() ),
('ZWD',716,'Zimbabwe dollar A/06','Y', NOW() )
;
