//
// this file is automatically generated
//
package org.marketcetera.eventbus.event;

/* $License$ */

/**
 * Creates new {@link SimpleEvent} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class SimpleEventFactory
        implements org.marketcetera.eventbus.event.EventFactory
{
    /**
     * Create a new <code>org.marketcetera.eventbus.event.SimpleEvent</code> instance.
     *
     * @return a <code>org.marketcetera.eventbus.event.SimpleEvent</code> value
     */
    @Override
    public org.marketcetera.eventbus.event.SimpleEvent create()
    {
        return new org.marketcetera.eventbus.event.SimpleEvent();
    }
    /**
     * Create a new <code>org.marketcetera.eventbus.event.SimpleEvent</code> instance from the given object.
     *
     * @param inEvent an <code>org.marketcetera.eventbus.event.SimpleEvent</code> value
     * @return an <code>org.marketcetera.eventbus.event.SimpleEvent</code> value
     */
    @Override
    public org.marketcetera.eventbus.event.SimpleEvent create(org.marketcetera.eventbus.event.Event inSimpleEvent)
    {
        return new org.marketcetera.eventbus.event.SimpleEvent(inSimpleEvent);
    }
}
