//
// this file is automatically generated
//
package org.marketcetera.eventbus.event;

/* $License$ */

/**
 * Creates new {@link Event} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface EventFactory
        extends org.marketcetera.core.Factory<Event>
{
    /**
     * Create a new <code>Event</code> instance.
     *
     * @return an <code>Event</code> value
     */
    @Override
    Event create();
    /**
     * Create a new <code>Event</code> instance from the given object.
     *
     * @param inEvent an <code>Event</code> value
     * @return an <code>Event</code> value
     */
    @Override
    Event create(Event inEvent);
}
