//
// this file is automatically generated
//
package org.marketcetera.eventbus.event;

/* $License$ */

/**
 * Creates {@link EventbusClient} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface EventbusClientFactory<ParameterClazz>
{
    /**
     * Create a new {@link EventbusClient} instance.
     *
     * @param inParameterClazz a <code>ParameterClazz</code> value
     * @return an <code>EventbusClient</code> value
     */
    EventbusClient create(ParameterClazz inParameterClazz);
}
