//
// this file is automatically generated
//
package org.marketcetera.eventbus.event;

/* $License$ */

/**
 * Indicates that something of interest has occurred.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface HasEvent
{
    /**
     * Get the event value.
     *
     * @return a <code>Event</code> value
     */
    Event getEvent();
    /**
     * Set the event value.
     *
     * @param inEvent a <code>Event</code> value
     */
    void setEvent(Event inEvent);
}
