//
// this file is automatically generated
//
package org.marketcetera.trade.pnl;

/* $License$ */

/**
 * Provides TradePnlServiceImpl services.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@org.springframework.stereotype.Component
public class TradePnlServiceImpl
        implements org.marketcetera.trade.pnl.TradePnlService
{
    /**
     * Requests positions for a user.
     *
     * @param inUserID a <code>org.marketcetera.trade.UserID</code> value
     * @param inPageRequest a <code>org.marketcetera.persist.PageRequest</code> value
     * @returns a <code>org.marketcetera.trade.pnl.Position</code> value
     */
    @Override
    @org.springframework.transaction.annotation.Transactional(readOnly=true,propagation=org.springframework.transaction.annotation.Propagation.REQUIRED)
    public org.marketcetera.persist.CollectionPageResponse<org.marketcetera.trade.pnl.Position> getCurrentPositions(org.marketcetera.trade.UserID inUserID,org.marketcetera.persist.PageRequest inPageRequest)
    {
        throw new UnsupportedOperationException(); // TODO
    }
    /**
     * Requests profit and loss for a user and an instrument.
     *
     * @param inUserID a <code>org.marketcetera.trade.UserID</code> value
     * @param inInstrument a <code>org.marketcetera.trade.Instrument</code> value
     * @param inPageRequest a <code>org.marketcetera.persist.PageRequest</code> value
     * @returns a <code>org.marketcetera.trade.pnl.ProfitAndLoss</code> value
     */
    @Override
    @org.springframework.transaction.annotation.Transactional(readOnly=true,propagation=org.springframework.transaction.annotation.Propagation.REQUIRED)
    public org.marketcetera.persist.CollectionPageResponse<org.marketcetera.trade.pnl.ProfitAndLoss> getProfitAndLoss(org.marketcetera.trade.UserID inUserID,org.marketcetera.trade.Instrument inInstrument,org.marketcetera.persist.PageRequest inPageRequest)
    {
        throw new UnsupportedOperationException(); // TODO
    }
}
