//
// this file is automatically generated
//
package org.marketcetera.eventbus.data.event;

import org.marketcetera.core.Preserve;
import org.marketcetera.rpc.client.RpcClientFactory;
import org.springframework.beans.factory.BeanCreationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

/* $License$ */

/**
 * Provides an RPC RpcClientFactory for DataEventRpc services.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@Preserve
public class DataEventRpcClientFactory
        implements DataEventClientFactory<DataEventRpcClientParameters>,RpcClientFactory<DataEventRpcClientParameters,DataEventRpcClient>
{
    /* (non-Javadoc)
     * @see org.marketcetera.eventbus.data.event.DataEventClientFactory#create(java.lang.Object)
     */
    @Override
    public DataEventRpcClient create(DataEventRpcClientParameters inParameterClazz)
    {
        try {
            return applicationContext.getBean(DataEventRpcClient.class,
                                              inParameterClazz);
        } catch (BeanCreationException e) {
            Throwable t = e.getCause();
            if(t instanceof RuntimeException) {
                throw (RuntimeException)t;
            }
            throw e;
        }
    }
    /**
     * provides access to the application context
     */
    @Autowired
    private ApplicationContext applicationContext;
}
