//
// this file is automatically generated
//
package org.marketcetera.eventbus.data.event;

/* $License$ */

/**
 * indicates that a data object has been added, changed, or deleted.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class SimpleDataChangeEvent
        implements DataChangeEvent
{
    /**
     * Create a new SimpleDataChangeEvent instance.
     */
    public SimpleDataChangeEvent() {}
    /**
     * Get the id value.
     *
     * @return a <code>long</code> value
     */
    @Override
    public long getId()
    {
        return id;
    }
    /**
     * Set the id value.
     *
     * @param inId a <code>long</code> value
     */
    public void setId(long inId)
    {
        id = inId;
    }
    /**
     * Get the timestamp value.
     *
     * @return a <code>java.util.Date</code> value
     */
    @Override
    public java.util.Date getTimestamp()
    {
        return timestamp;
    }
    /**
     * Set the timestamp value.
     *
     * @param inTimestamp a <code>java.util.Date</code> value
     */
    public void setTimestamp(java.util.Date inTimestamp)
    {
        timestamp = inTimestamp;
    }
    /**
     * Get the type value.
     *
     * @return a <code>java.lang.Class<?></code> value
     */
    @Override
    public java.lang.Class<?> getType()
    {
        return type;
    }
    /**
     * Set the type value.
     *
     * @param inType a <code>java.lang.Class<?></code> value
     */
    public void setType(java.lang.Class<?> inType)
    {
        type = inType;
    }
    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append("DataChangeEvent [")
            .append("id=").append(id)
            .append(", timestamp=").append(timestamp)
            .append(", type=").append(type).append("]");
        return builder.toString();
    }
    /**
     * id of the data object
     */
    private long id;
    /**
     * time when the data changed
     */
    private java.util.Date timestamp;
    /**
     * type of the event
     */
    private java.lang.Class<?> type;
}
