//
// this file is automatically generated
//
package org.marketcetera.strategy;

/* $License$ */

/**
 * Provides parameters for the StrategyRpc client.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class StrategyRpcClientParameters
        extends org.marketcetera.rpc.client.BaseRpcClientParameters
        implements StrategyClientParameters,org.marketcetera.rpc.client.RpcClientParameters
{
    /**
     * Create a new StrategyRpcClientParameters instance.
     */
    public StrategyRpcClientParameters () {}
    /**
     * Create a new StrategyRpcClientParameters instance.
     *
     * @param inHostname a <code>String</code> value
     * @param inPort an <code>int</code> value
     * @param inUsername a <code>String</code> value
     * @param inPassword a <code>String</code> value
     */
    public StrategyRpcClientParameters (String inHostname,int inPort,String inUsername,String inPassword)
    {
        setHostname(inHostname);
        setPort(inPort);
        setUsername(inUsername);
        setPassword(inPassword);
    }
}
