//
// this file is automatically generated
//
package org.marketcetera.strategy;

/* $License$ */

/**
 * Provides common behavior for Strategy services.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public abstract class StrategyRpcUtil
{
    /**
     * Get the RPC object from the given value.
     *
     * @param inStrategyInstance a <code>org.marketcetera.strategy.StrategyInstance</code> value
     * @return a java.util.Optional<StrategyTypesRpc.StrategyInstance> value
     */
    public static java.util.Optional<StrategyTypesRpc.StrategyInstance> getRpcStrategyInstance(org.marketcetera.strategy.StrategyInstance inStrategyInstance)
    {
        if(inStrategyInstance == null) {
            return java.util.Optional.empty();
        }
        StrategyTypesRpc.StrategyInstance.Builder builder = StrategyTypesRpc.StrategyInstance.newBuilder();
        org.marketcetera.admin.rpc.AdminRpcUtil.getRpcUser(inStrategyInstance.getUser()).ifPresent(value->builder.setUser(value));
        builder.setName(inStrategyInstance.getName());
        return java.util.Optional.of(builder.build());
    }
    /**
     * Get the object from the given RPC value.
     *
     * @param inStrategyInstance an <code>org.marketcetera.strategy.StrategyTypesRpc.StrategyInstance</code> value
     * @param inStrategyInstanceFactory an <code>org.marketcetera.strategy.StrategyInstanceFactory</code> value
     * @param inUserFactory an <code>org.marketcetera.admin.UserFactory</code> value
     * @return an org.marketcetera.strategy.StrategyInstance value
     */
    public static java.util.Optional<org.marketcetera.strategy.StrategyInstance> getStrategyInstance(org.marketcetera.strategy.StrategyTypesRpc.StrategyInstance inStrategyInstance,org.marketcetera.strategy.StrategyInstanceFactory inStrategyInstanceFactory,org.marketcetera.admin.UserFactory inUserFactory)
    {
        if(inStrategyInstance == null) {
            return java.util.Optional.empty();
        }
        org.marketcetera.strategy.StrategyInstance strategyInstance = inStrategyInstanceFactory.create();
        org.marketcetera.admin.rpc.AdminRpcUtil.getUser(inStrategyInstance.getUser(),inUserFactory).ifPresent(value->strategyInstance.setUser(value));
        strategyInstance.setName(inStrategyInstance.getName());
        return java.util.Optional.of(strategyInstance);
    }
}
