class InsertCurrencies < ActiveRecord::Migration
  def self.up
    Currency.new(:alpha_code => "AED", :numeric_code => 784, :description => "United Arab Emirates dirham", :obsolete => false).save()
    Currency.new(:alpha_code => "AFN", :numeric_code => 971, :description => "Afghani", :obsolete => false).save()
    Currency.new(:alpha_code => "ALL", :numeric_code => 8, :description => "Lek", :obsolete => false).save()
    Currency.new(:alpha_code => "AMD", :numeric_code => 51, :description => "Armenian Dram", :obsolete => false).save()
    Currency.new(:alpha_code => "ANG", :numeric_code => 532, :description => "Netherlands Antillian Guilder", :obsolete => false).save()
    Currency.new(:alpha_code => "AOA", :numeric_code => 973, :description => "Kwanza", :obsolete => false).save()
    Currency.new(:alpha_code => "ARS", :numeric_code => 32, :description => "Argentine Peso", :obsolete => false).save()
    Currency.new(:alpha_code => "AUD", :numeric_code => 36, :description => "Australian Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "AWG", :numeric_code => 533, :description => "Aruban Guilder", :obsolete => false).save()
    Currency.new(:alpha_code => "AZN", :numeric_code => 944, :description => "Azerbaijanian Manat", :obsolete => false).save()
    Currency.new(:alpha_code => "BAM", :numeric_code => 977, :description => "Convertible Marks", :obsolete => false).save()
    Currency.new(:alpha_code => "BBD", :numeric_code => 52, :description => "Barbados Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "BDT", :numeric_code => 50, :description => "Taka", :obsolete => false).save()
    Currency.new(:alpha_code => "BGN", :numeric_code => 975, :description => "Bulgarian Lev", :obsolete => false).save()
    Currency.new(:alpha_code => "BHD", :numeric_code => 48, :description => "Bahraini Dinar", :obsolete => false).save()
    Currency.new(:alpha_code => "BIF", :numeric_code => 108, :description => "Burundian Franc", :obsolete => false).save()
    Currency.new(:alpha_code => "BMD", :numeric_code => 60, :description => "Bermudian Dollar (customarily known as Bermuda Dollar)", :obsolete => false).save()
    Currency.new(:alpha_code => "BND", :numeric_code => 96, :description => "Brunei Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "BOB", :numeric_code => 68, :description => "Boliviano", :obsolete => false).save()
    Currency.new(:alpha_code => "BOV", :numeric_code => 984, :description => "Bolivian Mvdol (Funds code)", :obsolete => false).save()
    Currency.new(:alpha_code => "BRL", :numeric_code => 986, :description => "Brazilian Real", :obsolete => false).save()
    Currency.new(:alpha_code => "BSD", :numeric_code => 44, :description => "Bahamian Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "BTN", :numeric_code => 64, :description => "Ngultrum", :obsolete => false).save()
    Currency.new(:alpha_code => "BWP", :numeric_code => 72, :description => "Pula", :obsolete => false).save()
    Currency.new(:alpha_code => "BYR", :numeric_code => 974, :description => "Belarussian Ruble", :obsolete => false).save()
    Currency.new(:alpha_code => "BZD", :numeric_code => 84, :description => "Belize Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "CAD", :numeric_code => 124, :description => "Canadian Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "CDF", :numeric_code => 976, :description => "Franc Congolais", :obsolete => false).save()
    Currency.new(:alpha_code => "CHE", :numeric_code => 947, :description => "WIR Euro", :obsolete => false).save()
    Currency.new(:alpha_code => "CHF", :numeric_code => 756, :description => "Swiss Franc", :obsolete => false).save()
    Currency.new(:alpha_code => "CHW", :numeric_code => 948, :description => "WIR Franc", :obsolete => false).save()
    Currency.new(:alpha_code => "CLF", :numeric_code => 990, :description => "Unidades de formento (Funds code)", :obsolete => false).save()
    Currency.new(:alpha_code => "CLP", :numeric_code => 152, :description => "Chilean Peso", :obsolete => false).save()
    Currency.new(:alpha_code => "CNY", :numeric_code => 156, :description => "Yuan Renminbi", :obsolete => false).save()
    Currency.new(:alpha_code => "COP", :numeric_code => 170, :description => "Colombian Peso", :obsolete => false).save()
    Currency.new(:alpha_code => "COU", :numeric_code => 970, :description => "Unidad de Valor Real", :obsolete => false).save()
    Currency.new(:alpha_code => "CRC", :numeric_code => 188, :description => "Costa Rican Colon", :obsolete => false).save()
    Currency.new(:alpha_code => "CSD", :numeric_code => 891, :description => "Serbian Dinar", :obsolete => false).save()
    Currency.new(:alpha_code => "CUP", :numeric_code => 192, :description => "Cuban Peso", :obsolete => false).save()
    Currency.new(:alpha_code => "CVE", :numeric_code => 132, :description => "Cape Verde Escudo", :obsolete => false).save()
    Currency.new(:alpha_code => "CYP", :numeric_code => 196, :description => "Cyprus Pound", :obsolete => false).save()
    Currency.new(:alpha_code => "CZK", :numeric_code => 203, :description => "Czech Koruna", :obsolete => false).save()
    Currency.new(:alpha_code => "DJF", :numeric_code => 262, :description => "Djibouti Franc", :obsolete => false).save()
    Currency.new(:alpha_code => "DKK", :numeric_code => 208, :description => "Danish Krone", :obsolete => false).save()
    Currency.new(:alpha_code => "DOP", :numeric_code => 214, :description => "Dominican Peso", :obsolete => false).save()
    Currency.new(:alpha_code => "DZD", :numeric_code => 12, :description => "Algerian Dinar", :obsolete => false).save()
    Currency.new(:alpha_code => "EEK", :numeric_code => 233, :description => "Kroon", :obsolete => false).save()
    Currency.new(:alpha_code => "EGP", :numeric_code => 818, :description => "Egyptian Pound", :obsolete => false).save()
    Currency.new(:alpha_code => "ERN", :numeric_code => 232, :description => "Nakfa", :obsolete => false).save()
    Currency.new(:alpha_code => "ETB", :numeric_code => 230, :description => "Ethiopian Birr", :obsolete => false).save()
    Currency.new(:alpha_code => "EUR", :numeric_code => 978, :description => "Euro", :obsolete => false).save()
    Currency.new(:alpha_code => "FJD", :numeric_code => 242, :description => "Fiji Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "FKP", :numeric_code => 238, :description => "Falkland Islands Pound", :obsolete => false).save()
    Currency.new(:alpha_code => "GBP", :numeric_code => 826, :description => "Pound Sterling", :obsolete => false).save()
    Currency.new(:alpha_code => "GEL", :numeric_code => 981, :description => "Lari", :obsolete => false).save()
    Currency.new(:alpha_code => "GHC", :numeric_code => 288, :description => "Cedi", :obsolete => false).save()
    Currency.new(:alpha_code => "GIP", :numeric_code => 292, :description => "Gibraltar pound", :obsolete => false).save()
    Currency.new(:alpha_code => "GMD", :numeric_code => 270, :description => "Dalasi", :obsolete => false).save()
    Currency.new(:alpha_code => "GNF", :numeric_code => 324, :description => "Guinea Franc", :obsolete => false).save()
    Currency.new(:alpha_code => "GTQ", :numeric_code => 320, :description => "Quetzal", :obsolete => false).save()
    Currency.new(:alpha_code => "GYD", :numeric_code => 328, :description => "Guyana Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "HKD", :numeric_code => 344, :description => "Hong Kong Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "HNL", :numeric_code => 340, :description => "Lempira", :obsolete => false).save()
    Currency.new(:alpha_code => "HRK", :numeric_code => 191, :description => "Croatian Kuna", :obsolete => false).save()
    Currency.new(:alpha_code => "HTG", :numeric_code => 332, :description => "Haiti Gourde", :obsolete => false).save()
    Currency.new(:alpha_code => "HUF", :numeric_code => 348, :description => "Forint", :obsolete => false).save()
    Currency.new(:alpha_code => "IDR", :numeric_code => 360, :description => "Rupiah", :obsolete => false).save()
    Currency.new(:alpha_code => "ILS", :numeric_code => 376, :description => "New Israeli Shekel", :obsolete => false).save()
    Currency.new(:alpha_code => "INR", :numeric_code => 356, :description => "Indian Rupee", :obsolete => false).save()
    Currency.new(:alpha_code => "IQD", :numeric_code => 368, :description => "Iraqi Dinar", :obsolete => false).save()
    Currency.new(:alpha_code => "IRR", :numeric_code => 364, :description => "Iranian Rial", :obsolete => false).save()
    Currency.new(:alpha_code => "ISK", :numeric_code => 352, :description => "Iceland Krona", :obsolete => false).save()
    Currency.new(:alpha_code => "JMD", :numeric_code => 388, :description => "Jamaican Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "JOD", :numeric_code => 400, :description => "Jordanian Dinar", :obsolete => false).save()
    Currency.new(:alpha_code => "JPY", :numeric_code => 392, :description => "Japanese yen", :obsolete => false).save()
    Currency.new(:alpha_code => "KES", :numeric_code => 404, :description => "Kenyan Shilling", :obsolete => false).save()
    Currency.new(:alpha_code => "KGS", :numeric_code => 417, :description => "Som", :obsolete => false).save()
    Currency.new(:alpha_code => "KHR", :numeric_code => 116, :description => "Riel", :obsolete => false).save()
    Currency.new(:alpha_code => "KMF", :numeric_code => 174, :description => "Comoro Franc", :obsolete => false).save()
    Currency.new(:alpha_code => "KPW", :numeric_code => 408, :description => "North Korean Won", :obsolete => false).save()
    Currency.new(:alpha_code => "KRW", :numeric_code => 410, :description => "Won", :obsolete => false).save()
    Currency.new(:alpha_code => "KWD", :numeric_code => 414, :description => "Kuwaiti Dinar", :obsolete => false).save()
    Currency.new(:alpha_code => "KYD", :numeric_code => 136, :description => "Cayman Islands Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "KZT", :numeric_code => 398, :description => "Tenge", :obsolete => false).save()
    Currency.new(:alpha_code => "LAK", :numeric_code => 418, :description => "Kip", :obsolete => false).save()
    Currency.new(:alpha_code => "LBP", :numeric_code => 422, :description => "Lebanese Pound", :obsolete => false).save()
    Currency.new(:alpha_code => "LKR", :numeric_code => 144, :description => "Sri Lanka Rupee", :obsolete => false).save()
    Currency.new(:alpha_code => "LRD", :numeric_code => 430, :description => "Liberian Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "LSL", :numeric_code => 426, :description => "Loti", :obsolete => false).save()
    Currency.new(:alpha_code => "LTL", :numeric_code => 440, :description => "Lithuanian Litas", :obsolete => false).save()
    Currency.new(:alpha_code => "LVL", :numeric_code => 428, :description => "Latvian Lats", :obsolete => false).save()
    Currency.new(:alpha_code => "LYD", :numeric_code => 434, :description => "Libyan Dinar", :obsolete => false).save()
    Currency.new(:alpha_code => "MAD", :numeric_code => 504, :description => "Moroccan Dirham", :obsolete => false).save()
    Currency.new(:alpha_code => "MDL", :numeric_code => 498, :description => "Moldovan Leu", :obsolete => false).save()
    Currency.new(:alpha_code => "MGA", :numeric_code => 969, :description => "Malagasy Ariary", :obsolete => false).save()
    Currency.new(:alpha_code => "MKD", :numeric_code => 807, :description => "Denar", :obsolete => false).save()
    Currency.new(:alpha_code => "MMK", :numeric_code => 104, :description => "Kyat", :obsolete => false).save()
    Currency.new(:alpha_code => "MNT", :numeric_code => 496, :description => "Tugrik", :obsolete => false).save()
    Currency.new(:alpha_code => "MOP", :numeric_code => 446, :description => "Pataca", :obsolete => false).save()
    Currency.new(:alpha_code => "MRO", :numeric_code => 478, :description => "Ouguiya", :obsolete => false).save()
    Currency.new(:alpha_code => "MTL", :numeric_code => 470, :description => "Maltese Lira", :obsolete => false).save()
    Currency.new(:alpha_code => "MUR", :numeric_code => 480, :description => "Mauritius Rupee", :obsolete => false).save()
    Currency.new(:alpha_code => "MVR", :numeric_code => 462, :description => "Rufiyaa", :obsolete => false).save()
    Currency.new(:alpha_code => "MWK", :numeric_code => 454, :description => "Kwacha", :obsolete => false).save()
    Currency.new(:alpha_code => "MXN", :numeric_code => 484, :description => "Mexican Peso", :obsolete => false).save()
    Currency.new(:alpha_code => "MXV", :numeric_code => 979, :description => "Mexican Unidad de Inversion (UDI) (Funds code) (Mexico)", :obsolete => false).save()
    Currency.new(:alpha_code => "MYR", :numeric_code => 458, :description => "Malaysian Ringgit", :obsolete => false).save()
    Currency.new(:alpha_code => "MZN", :numeric_code => 943, :description => "Metical", :obsolete => false).save()
    Currency.new(:alpha_code => "NAD", :numeric_code => 516, :description => "Namibian Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "NGN", :numeric_code => 566, :description => "Naira", :obsolete => false).save()
    Currency.new(:alpha_code => "NIO", :numeric_code => 558, :description => "Cordoba Oro", :obsolete => false).save()
    Currency.new(:alpha_code => "NOK", :numeric_code => 578, :description => "Norwegian Krone", :obsolete => false).save()
    Currency.new(:alpha_code => "NPR", :numeric_code => 524, :description => "Nepalese Rupee", :obsolete => false).save()
    Currency.new(:alpha_code => "NZD", :numeric_code => 554, :description => "New Zealand Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "OMR", :numeric_code => 512, :description => "Rial Omani", :obsolete => false).save()
    Currency.new(:alpha_code => "PAB", :numeric_code => 590, :description => "Balboa", :obsolete => false).save()
    Currency.new(:alpha_code => "PEN", :numeric_code => 604, :description => "Nuevo Sol", :obsolete => false).save()
    Currency.new(:alpha_code => "PGK", :numeric_code => 598, :description => "Kina", :obsolete => false).save()
    Currency.new(:alpha_code => "PHP", :numeric_code => 608, :description => "Philippine Peso", :obsolete => false).save()
    Currency.new(:alpha_code => "PKR", :numeric_code => 586, :description => "Pakistan Rupee", :obsolete => false).save()
    Currency.new(:alpha_code => "PLN", :numeric_code => 985, :description => "Zloty", :obsolete => false).save()
    Currency.new(:alpha_code => "PYG", :numeric_code => 600, :description => "Guarani", :obsolete => false).save()
    Currency.new(:alpha_code => "QAR", :numeric_code => 634, :description => "Qatari Rial", :obsolete => false).save()
    Currency.new(:alpha_code => "ROL", :numeric_code => 642, :description => "Old Romanian Leu", :obsolete => false).save()
    Currency.new(:alpha_code => "RON", :numeric_code => 946, :description => "New Leu", :obsolete => false).save()
    Currency.new(:alpha_code => "RUB", :numeric_code => 643, :description => "Russian Ruble", :obsolete => false).save()
    Currency.new(:alpha_code => "RWF", :numeric_code => 646, :description => "Rwanda Franc", :obsolete => false).save()
    Currency.new(:alpha_code => "SAR", :numeric_code => 682, :description => "Saudi Riyal", :obsolete => false).save()
    Currency.new(:alpha_code => "SBD", :numeric_code => 90, :description => "Solomon Islands Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "SCR", :numeric_code => 690, :description => "Seychelles Rupee", :obsolete => false).save()
    Currency.new(:alpha_code => "SDD", :numeric_code => 736, :description => "Sudanese Dinar", :obsolete => false).save()
    Currency.new(:alpha_code => "SEK", :numeric_code => 752, :description => "Swedish Krona", :obsolete => false).save()
    Currency.new(:alpha_code => "SGD", :numeric_code => 702, :description => "Singapore Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "SHP", :numeric_code => 654, :description => "Saint Helena Pound", :obsolete => false).save()
    Currency.new(:alpha_code => "SIT", :numeric_code => 705, :description => "Tolar", :obsolete => false).save()
    Currency.new(:alpha_code => "SKK", :numeric_code => 703, :description => "Slovak Koruna", :obsolete => false).save()
    Currency.new(:alpha_code => "SLL", :numeric_code => 694, :description => "Leone", :obsolete => false).save()
    Currency.new(:alpha_code => "SOS", :numeric_code => 706, :description => "Somali Shilling", :obsolete => false).save()
    Currency.new(:alpha_code => "SRD", :numeric_code => 968, :description => "Surinam Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "STD", :numeric_code => 678, :description => "Dobra", :obsolete => false).save()
    Currency.new(:alpha_code => "SYP", :numeric_code => 760, :description => "Syrian Pound", :obsolete => false).save()
    Currency.new(:alpha_code => "SZL", :numeric_code => 748, :description => "Lilangeni", :obsolete => false).save()
    Currency.new(:alpha_code => "THB", :numeric_code => 764, :description => "Baht", :obsolete => false).save()
    Currency.new(:alpha_code => "TJS", :numeric_code => 972, :description => "Somoni", :obsolete => false).save()
    Currency.new(:alpha_code => "TMM", :numeric_code => 795, :description => "Manat", :obsolete => false).save()
    Currency.new(:alpha_code => "TND", :numeric_code => 788, :description => "Tunisian Dinar", :obsolete => false).save()
    Currency.new(:alpha_code => "TOP", :numeric_code => 776, :description => "Pa\anga", :obsolete => false).save()
    Currency.new(:alpha_code => "TRY", :numeric_code => 949, :description => "New Turkish Lira", :obsolete => false).save()
    Currency.new(:alpha_code => "TTD", :numeric_code => 780, :description => "Trinidad and Tobago Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "TWD", :numeric_code => 901, :description => "New Taiwan Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "TZS", :numeric_code => 834, :description => "Tanzanian Shilling", :obsolete => false).save()
    Currency.new(:alpha_code => "UAH", :numeric_code => 980, :description => "Hryvnia", :obsolete => false).save()
    Currency.new(:alpha_code => "UGX", :numeric_code => 800, :description => "Uganda Shilling", :obsolete => false).save()
    Currency.new(:alpha_code => "USD", :numeric_code => 840, :description => "US Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "USN", :numeric_code => 997, :description => nil, :obsolete => false).save()
    Currency.new(:alpha_code => "USS", :numeric_code => 998, :description => nil, :obsolete => false).save()
    Currency.new(:alpha_code => "UYU", :numeric_code => 858, :description => "Peso Uruguayo", :obsolete => false).save()
    Currency.new(:alpha_code => "UZS", :numeric_code => 860, :description => "Uzbekistan Som", :obsolete => false).save()
    Currency.new(:alpha_code => "VEB", :numeric_code => 862, :description => "Venezuelan bolivar", :obsolete => false).save()
    Currency.new(:alpha_code => "VND", :numeric_code => 704, :description => "Dong", :obsolete => false).save()
    Currency.new(:alpha_code => "VUV", :numeric_code => 548, :description => "Vatu", :obsolete => false).save()
    Currency.new(:alpha_code => "WST", :numeric_code => 882, :description => "Tala", :obsolete => false).save()
    Currency.new(:alpha_code => "XAF", :numeric_code => 950, :description => "CFA Franc BEAC", :obsolete => false).save()
    Currency.new(:alpha_code => "XAG", :numeric_code => 961, :description => "Silver (one Troy ounce)", :obsolete => false).save()
    Currency.new(:alpha_code => "XAU", :numeric_code => 959, :description => "Gold (one Troy ounce)", :obsolete => false).save()
    Currency.new(:alpha_code => "XBA", :numeric_code => 955, :description => "European Composite Unit (EURCO) (Bonds market unit)", :obsolete => false).save()
    Currency.new(:alpha_code => "XBB", :numeric_code => 956, :description => "European Monetary Unit (E.M.U.-6) (Bonds market unit)", :obsolete => false).save()
    Currency.new(:alpha_code => "XBC", :numeric_code => 957, :description => "European Unit of Account 9 (E.U.A.-9) (Bonds market unit)", :obsolete => false).save()
    Currency.new(:alpha_code => "XBD", :numeric_code => 958, :description => "European Unit of Account 17 (E.U.A.-17) (Bonds market unit)", :obsolete => false).save()
    Currency.new(:alpha_code => "XCD", :numeric_code => 951, :description => "East Caribbean Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "XDR", :numeric_code => 960, :description => "Special Drawing Rights", :obsolete => false).save()
    Currency.new(:alpha_code => "XFO", :numeric_code => nil, :description => "Gold-Franc (Special settlement currency)", :obsolete => false).save()
    Currency.new(:alpha_code => "XFU", :numeric_code => nil, :description => "UIC Franc (Special settlement currency)", :obsolete => false).save()
    Currency.new(:alpha_code => "XOF", :numeric_code => 952, :description => "CFA Franc BCEAO", :obsolete => false).save()
    Currency.new(:alpha_code => "XPD", :numeric_code => 964, :description => "Palladium (one Troy ounce)", :obsolete => false).save()
    Currency.new(:alpha_code => "XPF", :numeric_code => 953, :description => "CFP franc", :obsolete => false).save()
    Currency.new(:alpha_code => "XPT", :numeric_code => 962, :description => "Platinum (one Troy ounce)", :obsolete => false).save()
    Currency.new(:alpha_code => "XTS", :numeric_code => 963, :description => "Code reserved for testing purposes", :obsolete => false).save()
    Currency.new(:alpha_code => "XXX", :numeric_code => 999, :description => "No currency", :obsolete => false).save()
    Currency.new(:alpha_code => "YER", :numeric_code => 886, :description => "Yemeni Rial", :obsolete => false).save()
    Currency.new(:alpha_code => "ZAR", :numeric_code => 710, :description => "Rand", :obsolete => false).save()
    Currency.new(:alpha_code => "ZMK", :numeric_code => 894, :description => "Kwacha", :obsolete => false).save()
    Currency.new(:alpha_code => "ZWD", :numeric_code => 942, :description => "Zimbabwe Dollar", :obsolete => false).save()
    Currency.new(:alpha_code => "ADP", :numeric_code => 20, :description => "Andorran Peseta", :obsolete => true).save()
    Currency.new(:alpha_code => "ATS", :numeric_code => 40, :description => "Austrian Schilling", :obsolete => true).save()
    Currency.new(:alpha_code => "BEF", :numeric_code => 56, :description => "Belgian Franc", :obsolete => true).save()
    Currency.new(:alpha_code => "DEM", :numeric_code => 276, :description => "Deutsche Mark", :obsolete => true).save()
    Currency.new(:alpha_code => "ESP", :numeric_code => 724, :description => "Spanish Peseta", :obsolete => true).save()
    Currency.new(:alpha_code => "FIM", :numeric_code => 246, :description => "Finnish Markka", :obsolete => true).save()
    Currency.new(:alpha_code => "FRF", :numeric_code => 250, :description => "French Franc", :obsolete => true).save()
    Currency.new(:alpha_code => "GRD", :numeric_code => 300, :description => "Greek Drachma", :obsolete => true).save()
    Currency.new(:alpha_code => "IEP", :numeric_code => 372, :description => "Irish Pound", :obsolete => true).save()
    Currency.new(:alpha_code => "ITL", :numeric_code => 380, :description => "Italian Lira", :obsolete => true).save()
    Currency.new(:alpha_code => "LUF", :numeric_code => 442, :description => "Luxembourg Franc", :obsolete => true).save()
    Currency.new(:alpha_code => "NLG", :numeric_code => 528, :description => "Netherlands Guilder", :obsolete => true).save()
    Currency.new(:alpha_code => "PTE", :numeric_code => 620, :description => "Portuguese Escudo", :obsolete => true).save()
    Currency.new(:alpha_code => "XEU", :numeric_code => 954, :description => "European Currency Unit", :obsolete => true).save()
    Currency.new(:alpha_code => "ADF", :numeric_code => nil, :description => "Andorran Franc", :obsolete => true).save()
    Currency.new(:alpha_code => "AFA", :numeric_code => 4, :description => "Afghani", :obsolete => true).save()
    Currency.new(:alpha_code => "ALK", :numeric_code => nil, :description => "Albanian old lek", :obsolete => true).save()
    Currency.new(:alpha_code => "AON", :numeric_code => 24, :description => "Angolan New Kwanza", :obsolete => true).save()
    Currency.new(:alpha_code => "AOR", :numeric_code => 982, :description => "Angolan Kwanza Readjustado", :obsolete => true).save()
    Currency.new(:alpha_code => "ARP", :numeric_code => nil, :description => "Peso Argentino", :obsolete => true).save()
    Currency.new(:alpha_code => "ARY", :numeric_code => nil, :description => "Argentine peso", :obsolete => true).save()
    Currency.new(:alpha_code => "AZM", :numeric_code => 31, :description => "Azerbaijani manat", :obsolete => true).save()
    Currency.new(:alpha_code => "BEC", :numeric_code => 993, :description => "Belgian Franc (convertible)", :obsolete => true).save()
    Currency.new(:alpha_code => "BEL", :numeric_code => 992, :description => "Belgian Franc (financial)", :obsolete => true).save()
    Currency.new(:alpha_code => "BGJ", :numeric_code => nil, :description => "Bulgarian lev A/52", :obsolete => true).save()
    Currency.new(:alpha_code => "BGK", :numeric_code => nil, :description => "Bulgarian lev A/62", :obsolete => true).save()
    Currency.new(:alpha_code => "BGL", :numeric_code => 100, :description => "Bulgarian lev A/99", :obsolete => true).save()
    Currency.new(:alpha_code => "BOP", :numeric_code => nil, :description => "Bolivian peso", :obsolete => true).save()
    Currency.new(:alpha_code => "BRB", :numeric_code => nil, :description => "Brazilian cruzeiro", :obsolete => true).save()
    Currency.new(:alpha_code => "BRC", :numeric_code => nil, :description => "Brazilian cruzado", :obsolete => true).save()
    Currency.new(:alpha_code => "CNX", :numeric_code => nil, :description => "Chinese People\s Bank dollar", :obsolete => true).save()
    Currency.new(:alpha_code => "CSJ", :numeric_code => nil, :description => "Czechoslovak koruna A/53", :obsolete => true).save()
    Currency.new(:alpha_code => "CSK", :numeric_code => 200, :description => "Czechoslovak koruna", :obsolete => true).save()
    Currency.new(:alpha_code => "DDM", :numeric_code => 278, :description => "mark der DDR (East Germany)", :obsolete => true).save()
    Currency.new(:alpha_code => "ECS", :numeric_code => 218, :description => "Ecuador sucre", :obsolete => true).save()
    Currency.new(:alpha_code => "ECV", :numeric_code => 983, :description => "Ecuador Unidad de Valor Constante (Funds code) (discontinued)", :obsolete => true).save()
    Currency.new(:alpha_code => "EQE", :numeric_code => nil, :description => "Equatorial Guinean ekwele", :obsolete => true).save()
    Currency.new(:alpha_code => "ESA", :numeric_code => 996, :description => "Spanish peseta (account A)", :obsolete => true).save()
    Currency.new(:alpha_code => "ESB", :numeric_code => 995, :description => "Spanish peseta (account B)", :obsolete => true).save()
    Currency.new(:alpha_code => "GNE", :numeric_code => nil, :description => "Guinean syli", :obsolete => true).save()
    Currency.new(:alpha_code => "GWP", :numeric_code => 624, :description => "Guinea peso", :obsolete => true).save()
    Currency.new(:alpha_code => "ILP", :numeric_code => nil, :description => "Israeli pound", :obsolete => true).save()
    Currency.new(:alpha_code => "ILR", :numeric_code => nil, :description => "Israeli old shekel", :obsolete => true).save()
    Currency.new(:alpha_code => "ISJ", :numeric_code => nil, :description => "Icelandic old krona", :obsolete => true).save()
    Currency.new(:alpha_code => "LAJ", :numeric_code => nil, :description => "Lao kip - Pot Pol", :obsolete => true).save()
    Currency.new(:alpha_code => "MAF", :numeric_code => nil, :description => "Mali franc", :obsolete => true).save()
    Currency.new(:alpha_code => "MGF", :numeric_code => 450, :description => "Malagasy franc", :obsolete => true).save()
    Currency.new(:alpha_code => "MKN", :numeric_code => nil, :description => "Macedonian denar A/93", :obsolete => true).save()
    Currency.new(:alpha_code => "MVQ", :numeric_code => nil, :description => "Maldive rupee", :obsolete => true).save()
    Currency.new(:alpha_code => "MXP", :numeric_code => nil, :description => "Mexican peso", :obsolete => true).save()
    Currency.new(:alpha_code => "MZM", :numeric_code => 508, :description => "Metical", :obsolete => true).save()
    Currency.new(:alpha_code => "PEH", :numeric_code => nil, :description => "Peruvian sol", :obsolete => true).save()
    Currency.new(:alpha_code => "PEI", :numeric_code => nil, :description => "Peruvian inti", :obsolete => true).save()
    Currency.new(:alpha_code => "PLZ", :numeric_code => 616, :description => "Polish zloty A/94", :obsolete => true).save()
    Currency.new(:alpha_code => "ROK", :numeric_code => nil, :description => "Romanian leu A/52", :obsolete => true).save()
    Currency.new(:alpha_code => "RUR", :numeric_code => 810, :description => "Russian ruble", :obsolete => true).save()
    Currency.new(:alpha_code => "SRG", :numeric_code => 740, :description => "Suriname guilder", :obsolete => true).save()
    Currency.new(:alpha_code => "SUR", :numeric_code => nil, :description => "Soviet Union ruble", :obsolete => true).save()
    Currency.new(:alpha_code => "SVC", :numeric_code => 222, :description => "Salvadoran colon", :obsolete => true).save()
    Currency.new(:alpha_code => "TJR", :numeric_code => 762, :description => "tjr", :obsolete => true).save()
    Currency.new(:alpha_code => "TPE", :numeric_code => 626, :description => "Timor escudo", :obsolete => true).save()
    Currency.new(:alpha_code => "TRL", :numeric_code => 792, :description => "Turkish lira A/05", :obsolete => true).save()
    Currency.new(:alpha_code => "UAK", :numeric_code => 804, :description => "Ukrainian karbovanets", :obsolete => true).save()
    Currency.new(:alpha_code => "UGW", :numeric_code => nil, :description => "Ugandan old shilling", :obsolete => true).save()
    Currency.new(:alpha_code => "UYN", :numeric_code => nil, :description => "Uruguay old peso", :obsolete => true).save()
    Currency.new(:alpha_code => "VNC", :numeric_code => nil, :description => "Vietnamese old dong", :obsolete => true).save()
    Currency.new(:alpha_code => "YDD", :numeric_code => 720, :description => "South Yemeni dinar", :obsolete => true).save()
    Currency.new(:alpha_code => "YUD", :numeric_code => nil, :description => "New Yugoslavian Dinar", :obsolete => true).save()
    Currency.new(:alpha_code => "ZAL", :numeric_code => 991, :description => "South African financial rand (Funds code) (discontinued)", :obsolete => true).save()
    Currency.new(:alpha_code => "ZRN", :numeric_code => 180, :description => "New Zaire", :obsolete => true).save()
    Currency.new(:alpha_code => "ZRZ", :numeric_code => nil, :description => "Zaire", :obsolete => true).save()
    Currency.new(:alpha_code => "ZWC", :numeric_code => nil, :description => "Zimbabwe Rhodesian dollar", :obsolete => true).save()
  end

  def self.down
    #Currency.delete_all
  end
end
