//
// this file is automatically generated
//
package org.marketcetera.trade.pnl.dao;

/* $License$ */

/**
 * Describes the current position of a given instrument owned by a given user.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface CurrentPositionDao
        extends org.springframework.data.jpa.repository.JpaRepository<PersistentCurrentPosition,Long>,org.springframework.data.querydsl.QuerydslPredicateExecutor<PersistentCurrentPosition>
{
}
