//
// this file is automatically generated
//
package org.marketcetera.trade.pnl.dao;

import org.marketcetera.core.Preserve;
import org.marketcetera.trade.pnl.Position;
import org.marketcetera.trade.pnl.PositionFactory;

/* $License$ */

/**
 * Creates new {@link PersistentPosition} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@Preserve
public class PersistentPositionFactory
        implements PositionFactory
{
    /**
     * Create a new <code>PersistentPosition</code> instance.
     *
     * @return a <code>PersistentPosition</code> value
     */
    @Override
    public PersistentPosition create()
    {
        return new PersistentPosition();
    }
    /**
     * Create a new <code>PersistentPosition</code> instance from the given object.
     *
     * @param inPosition a <code>Position</code> value
     * @return a <code>PersistentPosition</code> value
     */
    @Override
    public PersistentPosition create(Position inPosition)
    {
        return new PersistentPosition(inPosition);
    }
}
