//
// this file is automatically generated
//
package org.marketcetera.trade.pnl.dao;

import org.marketcetera.core.Preserve;
import org.marketcetera.trade.pnl.ProfitAndLoss;
import org.marketcetera.trade.pnl.ProfitAndLossFactory;

/* $License$ */

/**
 * Creates new {@link PersistentProfitAndLoss} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@Preserve
public class PersistentProfitAndLossFactory
        implements ProfitAndLossFactory
{
    /**
     * Create a new <code>PersistentProfitAndLoss</code> instance.
     *
     * @return a <code>PersistentProfitAndLoss</code> value
     */
    @Override
    public PersistentProfitAndLoss create()
    {
        return new PersistentProfitAndLoss();
    }
    /**
     * Create a new <code>PersistentProfitAndLoss</code> instance from the given object.
     *
     * @param inProfitAndLoss a <code>ProfitAndLoss</code> value
     * @return a <code>PersistentProfitAndLoss</code> value
     */
    @Override
    public PersistentProfitAndLoss create(ProfitAndLoss inProfitAndLoss)
    {
        return new PersistentProfitAndLoss(inProfitAndLoss);
    }
}
