//
// this file is automatically generated
//
package org.marketcetera.trade.pnl.dao;

/* $License$ */

/**
 * Creates new {@link PersistentPosition} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class PersistentPositionFactory
        implements org.marketcetera.trade.pnl.PositionFactory
{
    /**
     * Create a new <code>org.marketcetera.trade.pnl.dao.PersistentPosition</code> instance.
     *
     * @return a <code>org.marketcetera.trade.pnl.dao.PersistentPosition</code> value
     */
    @Override
    public org.marketcetera.trade.pnl.dao.PersistentPosition create()
    {
        return new org.marketcetera.trade.pnl.dao.PersistentPosition();
    }
    /**
     * Create a new <code>org.marketcetera.trade.pnl.dao.PersistentPosition</code> instance from the given object.
     *
     * @param inPosition an <code>org.marketcetera.trade.pnl.dao.PersistentPosition</code> value
     * @return an <code>org.marketcetera.trade.pnl.dao.PersistentPosition</code> value
     */
    @Override
    public org.marketcetera.trade.pnl.dao.PersistentPosition create(org.marketcetera.trade.pnl.Position inPersistentPosition)
    {
        return new org.marketcetera.trade.pnl.dao.PersistentPosition(inPersistentPosition);
    }
}
