//
// this file is automatically generated
//
package org.marketcetera.trade.pnl.dao;

/* $License$ */

/**
 * Creates new {@link PersistentCurrentPosition} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class PersistentCurrentPositionFactory
        implements org.marketcetera.trade.pnl.CurrentPositionFactory
{
    /**
     * Create a new <code>org.marketcetera.trade.pnl.dao.PersistentCurrentPosition</code> instance.
     *
     * @return a <code>org.marketcetera.trade.pnl.dao.PersistentCurrentPosition</code> value
     */
    @Override
    public org.marketcetera.trade.pnl.dao.PersistentCurrentPosition create()
    {
        return new org.marketcetera.trade.pnl.dao.PersistentCurrentPosition();
    }
    /**
     * Create a new <code>org.marketcetera.trade.pnl.dao.PersistentCurrentPosition</code> instance from the given object.
     *
     * @param inObject a <code>org.marketcetera.trade.pnl.dao.PersistentCurrentPosition</code> value
     * @return a <code>org.marketcetera.trade.pnl.dao.PersistentCurrentPosition</code> value
     */
    @Override
    public org.marketcetera.trade.pnl.dao.PersistentCurrentPosition create(org.marketcetera.trade.pnl.CurrentPosition inPersistentCurrentPosition)
    {
        return new org.marketcetera.trade.pnl.dao.PersistentCurrentPosition(inPersistentCurrentPosition);
    }
}
