//
// this file is automatically generated
//
package org.marketcetera.trade.pnl.dao;

/* $License$ */

/**
 * Indicates profit and loss for a user-instrument tuple.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface ProfitAndLossDao
        extends org.springframework.data.jpa.repository.JpaRepository<PersistentProfitAndLoss,Long>,org.springframework.data.querydsl.QuerydslPredicateExecutor<PersistentProfitAndLoss>
{
}
