//
// this file is automatically generated
//
package org.marketcetera.trade.pnl.dao;

/* $License$ */

/**
 * Provides a user-centric view of a {@link Trade}.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface UserTradeDao
        extends org.springframework.data.jpa.repository.JpaRepository<PersistentUserTrade,Long>,org.springframework.data.querydsl.QuerydslPredicateExecutor<PersistentUserTrade>
{
}
