//
// this file is automatically generated
//
package org.marketcetera.eventbus.data.event;

/* $License$ */

/**
 * Provides DataEventServiceImpl services.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@org.springframework.stereotype.Component
public class DataEventServiceImpl
        implements org.marketcetera.eventbus.data.event.DataEventService
{
    /**
     * Requests data events.
     *
     * @param inString a <code>String</code> value
     * @param inClass<?s a <code>java.util.Collection&lt;Class<?>&gt;</code> value
     * @param inConsumer<DataEvent a <code>java.util.function.Consumer<DataEvent></code> value
     */
    @Override
    @org.springframework.transaction.annotation.Transactional(readOnly=true,propagation=org.springframework.transaction.annotation.Propagation.REQUIRED)
    public void subscribeToDataEvents(String inString,java.util.Collection<Class<?>> inClass,java.util.function.Consumer<DataEvent> inConsumer)
    {
        throw new UnsupportedOperationException(); // TODO
    }
    /**
     * Cancels data event request.
     *
     * @param inString a <code>String</code> value
     */
    @Override
    @org.springframework.transaction.annotation.Transactional(readOnly=true,propagation=org.springframework.transaction.annotation.Propagation.REQUIRED)
    public void unSubscribeToDataEvents(String inString)
    {
        throw new UnsupportedOperationException(); // TODO
    }
    /**
     * Accept incoming DataEvent values.
     */
    @com.google.common.eventbus.Subscribe
    public void accept(org.marketcetera.eventbus.data.event.DataEvent inDataEvent)
    {
        throw new UnsupportedOperationException(); // TODO
    }
    /**
     * Validate and start the object.
     */
    @javax.annotation.PostConstruct
    public void start()
    {
        org.marketcetera.util.log.SLF4JLoggerProxy.info(this,"Starting {}",org.marketcetera.core.PlatformServices.getServiceName(getClass()));
        eventBusService.register(this);
    }
    /**
     * provides access to event services
     */
    @org.springframework.beans.factory.annotation.Autowired
    private org.marketcetera.eventbus.EventBusService eventBusService;
}
