//
// this file is automatically generated
//
package org.marketcetera.strategy;

import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import org.marketcetera.core.Preserve;
import org.marketcetera.core.notifications.INotification;

/* $License$ */

/**
 * Represents a message emitted by a strategy.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@Preserve
public class SimpleStrategyMessage
        implements StrategyMessage
{
    /**
     * Create a new SimpleStrategyMessage instance.
     */
    public SimpleStrategyMessage() {}
    /**
     * Create a new SimpleStrategyMessage instance.
     *
     * @param inStrategyMessage a <code>StrategyMessage</code> value
     */
    public SimpleStrategyMessage(StrategyMessage inStrategyMessage)
    {
        setStrategyInstance(inStrategyMessage.getStrategyInstance());
        setStrategyMessageId(inStrategyMessage.getStrategyMessageId());
        setMessageTimestamp(inStrategyMessage.getMessageTimestamp());
        setSeverity(inStrategyMessage.getSeverity());
        setMessage(inStrategyMessage.getMessage());
    }
    /**
     * Get the strategyInstance value.
     *
     * @return a <code>StrategyInstance</code> value
     */
    @Override
    public StrategyInstance getStrategyInstance()
    {
        return strategyInstance;
    }
    /**
     * Set the strategyInstance value.
     *
     * @param inStrategyInstance a <code>StrategyInstance</code> value
     */
    @Override
    public void setStrategyInstance(StrategyInstance inStrategyInstance)
    {
        strategyInstance = inStrategyInstance;
    }
    /**
     * Get the messageTimestamp value.
     *
     * @return a <code>Date</code> value
     */
    @Override
    public Date getMessageTimestamp()
    {
        return messageTimestamp;
    }
    /**
     * Set the messageTimestamp value.
     *
     * @param inMessageTimestamp a <code>Date</code> value
     */
    @Override
    public void setMessageTimestamp(Date inMessageTimestamp)
    {
        messageTimestamp = inMessageTimestamp;
    }
    /**
     * Get the severity value.
     *
     * @return an <code>INotification.Severity</code> value
     */
    @Override
    public INotification.Severity getSeverity()
    {
        return severity;
    }
    /**
     * Set the severity value.
     *
     * @param inSeverity an <code>INotification.Severity</code> value
     */
    @Override
    public void setSeverity(INotification.Severity inSeverity)
    {
        severity = inSeverity;
    }
    /* (non-Javadoc)
     * @see StrategyMessage#getStrategyMessageId()
     */
    @Override
    public long getStrategyMessageId()
    {
        return strategyMessageId;
    }
    /**
     * Get the message value.
     *
     * @return a <code>String</code> value
     */
    @Override
    public String getMessage()
    {
        return message;
    }
    /**
     * Set the message value.
     *
     * @param inMessage a <code>String</code> value
     */
    @Override
    public void setMessage(String inMessage)
    {
        message = StringUtils.trimToNull(inMessage);
    }
    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append("StrategyMessage [")
            .append("strategyMessageId=").append(strategyMessageId)
            .append(", strategyInstance=").append(strategyInstance)
            .append(", messageTimestamp=").append(messageTimestamp)
            .append(", severity=").append(severity)
            .append(", message=").append(message).append("]");
        return builder.toString();
    }
    /**
     * Sets the strategyMessageId value.
     *
     * @param inStrategyMessageId a <code>long</code> value
     */
    public void setStrategyMessageId(long inStrategyMessageId)
    {
        strategyMessageId = inStrategyMessageId;
    }
    /**
     * strategy which created this message
     */
    private StrategyInstance strategyInstance;
    /**
     * date message was created
     */
    private Date messageTimestamp;
    /**
     * strategy message severity
     */
    private INotification.Severity severity;
    /**
     * message from the strategy
     */
    private String message;
    /**
     * uniquely identifies this message
     */
    private long strategyMessageId;
}
