//
// this file is automatically generated
//
package org.marketcetera.strategy;

/* $License$ */

/**
 * Identifies a unique strategy instance.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class SimpleStrategyInstance
        implements StrategyInstance
{
    /**
     * Create a new SimpleStrategyInstance instance.
     */
    public SimpleStrategyInstance() {}
    /**
     * Create a new SimpleStrategyInstance instance.
     *
     * @param inStrategyInstance a <code>StrategyInstance</code> value
     */
    public SimpleStrategyInstance(StrategyInstance inStrategyInstance)
    {
        setUser(inStrategyInstance.getUser());
        setName(inStrategyInstance.getName());
        setFilename(inStrategyInstance.getFilename());
        setHash(inStrategyInstance.getHash());
        setNonce(inStrategyInstance.getNonce());
        setStarted(inStrategyInstance.getStarted());
        setStatus(inStrategyInstance.getStatus());
    }
    /**
     * Get the user value.
     *
     * @return an <code>org.marketcetera.admin.User</code> value
     */
    @Override
    public org.marketcetera.admin.User getUser()
    {
        return user;
    }
    /**
     * Set the user value.
     *
     * @param inUser an <code>org.marketcetera.admin.User</code> value
     */
    @Override
    public void setUser(org.marketcetera.admin.User inUser)
    {
        user = inUser;
    }
    /**
     * Get the name value.
     *
     * @return a <code>String</code> value
     */
    @Override
    public String getName()
    {
        return name;
    }
    /**
     * Set the name value.
     *
     * @param inName a <code>String</code> value
     */
    @Override
    public void setName(String inName)
    {
        name = org.apache.commons.lang3.StringUtils.trimToNull(inName);
    }
    /**
     * Get the filename value.
     *
     * @return a <code>String</code> value
     */
    @Override
    public String getFilename()
    {
        return filename;
    }
    /**
     * Set the filename value.
     *
     * @param inFilename a <code>String</code> value
     */
    @Override
    public void setFilename(String inFilename)
    {
        filename = org.apache.commons.lang3.StringUtils.trimToNull(inFilename);
    }
    /**
     * Get the hash value.
     *
     * @return a <code>String</code> value
     */
    @Override
    public String getHash()
    {
        return hash;
    }
    /**
     * Set the hash value.
     *
     * @param inHash a <code>String</code> value
     */
    @Override
    public void setHash(String inHash)
    {
        hash = org.apache.commons.lang3.StringUtils.trimToNull(inHash);
    }
    /**
     * Get the nonce value.
     *
     * @return a <code>String</code> value
     */
    @Override
    public String getNonce()
    {
        return nonce;
    }
    /**
     * Set the nonce value.
     *
     * @param inNonce a <code>String</code> value
     */
    @Override
    public void setNonce(String inNonce)
    {
        nonce = org.apache.commons.lang3.StringUtils.trimToNull(inNonce);
    }
    /**
     * Get the started value.
     *
     * @return a <code>java.util.Date</code> value
     */
    @Override
    public java.util.Date getStarted()
    {
        return started;
    }
    /**
     * Set the started value.
     *
     * @param inStarted a <code>java.util.Date</code> value
     */
    @Override
    public void setStarted(java.util.Date inStarted)
    {
        started = inStarted;
    }
    /**
     * Get the status value.
     *
     * @return an <code>org.marketcetera.strategy.StrategyStatus</code> value
     */
    @Override
    public org.marketcetera.strategy.StrategyStatus getStatus()
    {
        return status;
    }
    /**
     * Set the status value.
     *
     * @param inStatus an <code>org.marketcetera.strategy.StrategyStatus</code> value
     */
    @Override
    public void setStatus(org.marketcetera.strategy.StrategyStatus inStatus)
    {
        status = inStatus;
    }
    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append("StrategyInstance [")
            .append("user=").append(user)
            .append(", name=").append(name)
            .append(", filename=").append(filename)
            .append(", hash=").append(hash)
            .append(", nonce=").append(nonce)
            .append(", started=").append(started)
            .append(", status=").append(status).append("]");
        return builder.toString();
    }
    /**
     * user which owns this strategy
     */
    private org.marketcetera.admin.User user;
    /**
     * uniquely describes the strategy
     */
    private String name;
    /**
     * indicates the server-local file which contains the strategy
     */
    private String filename;
    /**
     * indicates the strategy hash value
     */
    private String hash;
    /**
     * uniquely identifies a strategy upload request
     */
    private String nonce;
    /**
     * date strategy was started
     */
    private java.util.Date started;
    /**
     * describes the state of a loaded strategy
     */
    private org.marketcetera.strategy.StrategyStatus status;
}
