//
// this file is automatically generated
//
package org.marketcetera.strategy.events;

/* $License$ */

/**
 * Indicates that a strategy message was added.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface StrategyMessageEvent
        extends org.marketcetera.strategy.HasStrategyMessage,org.marketcetera.strategy.events.StrategyEvent
{
}
