//
// this file is automatically generated
//
package org.marketcetera.strategy.events;

/* $License$ */

/**
 * Indicates that a strategy upload failed.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface StrategyUploadFailedEvent
        extends org.marketcetera.strategy.HasStrategyInstance,org.marketcetera.strategy.events.StrategyEvent
{
    /**
     * Get the errorMessage value.
     *
     * @return a <code>String</code> value
     */
    String getErrorMessage();
    /**
     * Set the errorMessage value.
     *
     * @param inErrorMessage a <code>String</code> value
     */
    void setErrorMessage(String inErrorMessage);
}
