//
// this file is automatically generated
//
package org.marketcetera.strategy.events;

/* $License$ */

/**
 * Indicates that a strategy was stopped.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface StrategyStoppedEvent
        extends org.marketcetera.strategy.events.StrategyEvent,org.marketcetera.strategy.HasStrategyInstance
{
}
