alter table reports add column transact_time timestamp without time zone;
update reports set transact_time=send_time;
alter table reports alter column transact_time SET NOT NULL;

alter table reports add column text character varying(255);

alter table exec_reports add column broker_order_id character varying(255);
update exec_reports set broker_order_id='unknown';
alter table exec_reports alter column broker_order_id SET NOT NULL;

alter table exec_reports add column exec_id character varying(255);
update exec_reports set exec_id='unknown';
alter table exec_reports alter column exec_id SET NOT NULL;

alter table exec_reports add column new_exec_type character varying(255);
update exec_reports set new_exec_type='Unknown' where exec_type=0;
update exec_reports set new_exec_type='New' where exec_type=1;
update exec_reports set new_exec_type='PartialFill' where exec_type=2;
update exec_reports set new_exec_type='Fill' where exec_type=3;
update exec_reports set new_exec_type='DoneForDay' where exec_type=4;
update exec_reports set new_exec_type='Canceled' where exec_type=5;
update exec_reports set new_exec_type='Replace' where exec_type=6;
update exec_reports set new_exec_type='PendingCancel' where exec_type=7;
update exec_reports set new_exec_type='Stopped' where exec_type=8;
update exec_reports set new_exec_type='Rejected' where exec_type=9;
update exec_reports set new_exec_type='Suspended' where exec_type=10;
update exec_reports set new_exec_type='PendingNew' where exec_type=11;
update exec_reports set new_exec_type='Calculated' where exec_type=12;
update exec_reports set new_exec_type='Expired' where exec_type=13;
update exec_reports set new_exec_type='Restated' where exec_type=14;
update exec_reports set new_exec_type='PendingReplace' where exec_type=15;
update exec_reports set new_exec_type='Trade' where exec_type=16;
update exec_reports set new_exec_type='TradeCorrect' where exec_type=17;
update exec_reports set new_exec_type='TradeCancel' where exec_type=18;
update exec_reports set new_exec_type='OrderStatus' where exec_type=19;
alter table exec_reports drop column exec_type;
alter table exec_reports add column exec_type character varying(255);
update exec_reports set exec_type=new_exec_type;
alter table exec_reports alter column exec_type SET NOT NULL;
alter table exec_reports drop column new_exec_type;

alter table exec_reports add column new_ord_status character varying(255);
update exec_reports set new_ord_status='Unknown' where ord_status=0;
update exec_reports set new_ord_status='New' where ord_status=1;
update exec_reports set new_ord_status='PartialFilled' where ord_status=2;
update exec_reports set new_ord_status='Filled' where ord_status=3;
update exec_reports set new_ord_status='DoneForDay' where ord_status=4;
update exec_reports set new_ord_status='Canceled' where ord_status=5;
update exec_reports set new_ord_status='Replaced' where ord_status=6;
update exec_reports set new_ord_status='PendingCancel' where ord_status=7;
update exec_reports set new_ord_status='Stopped' where ord_status=8;
update exec_reports set new_ord_status='Rejected' where ord_status=9;
update exec_reports set new_ord_status='Suspended' where ord_status=10;
update exec_reports set new_ord_status='PendingNew' where ord_status=11;
update exec_reports set new_ord_status='Calculated' where ord_status=12;
update exec_reports set new_ord_status='Expired' where ord_status=13;
update exec_reports set new_ord_status='AcceptedForBidding' where ord_status=14;
update exec_reports set new_ord_status='PendingReplace' where ord_status=15;
alter table exec_reports drop column ord_status;
alter table exec_reports add column ord_status character varying(255);
update exec_reports set ord_status=new_ord_status;
alter table exec_reports alter column ord_status SET NOT NULL;
alter table exec_reports drop column new_ord_status;

alter table exec_reports add column new_security_type character varying(255);
update exec_reports set new_security_type='Unknown' where security_type=0;
update exec_reports set new_security_type='CommonStock' where security_type=1;
update exec_reports set new_security_type='Option' where security_type=2;
update exec_reports set new_security_type='Future' where security_type=3;
update exec_reports set new_security_type='ConvertibleBond' where security_type=4;
update exec_reports set new_security_type='Currency' where security_type=5;
alter table exec_reports drop column security_type;
alter table exec_reports add column security_type character varying(255);
update exec_reports set security_type=new_security_type;
alter table exec_reports alter column security_type SET NOT NULL;
alter table exec_reports drop column new_security_type;

alter table exec_reports add column new_side character varying(255);
update exec_reports set new_side='Unknown' where side=0;
update exec_reports set new_side='Buy' where side=1;
update exec_reports set new_side='Sell' where side=2;
update exec_reports set new_side='SellShort' where side=3;
update exec_reports set new_side='SellShortExempt' where side=4;
update exec_reports set new_side='BuyMinus' where side=5;
update exec_reports set new_side='Cross' where side=6;
update exec_reports set new_side='CrossShort' where side=7;
update exec_reports set new_side='SellPlus' where side=8;
update exec_reports set new_side='Undisclosed' where side=9;
alter table exec_reports drop column side;
alter table exec_reports add column side character varying(255);
update exec_reports set side=new_side;
alter table exec_reports alter column side SET NOT NULL;
alter table exec_reports drop column new_side;
