//
// this file is automatically generated
//
package org.marketcetera.strategy;

/* $License$ */

/**
 * Represents a message emitted by a strategy.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface HasStrategyMessage
{
    /**
     * Get the strategymessage value.
     *
     * @return a <code>StrategyMessage</code> value
     */
    StrategyMessage getStrategyMessage();
    /**
     * Set the strategymessage value.
     *
     * @param inStrategyMessage a <code>StrategyMessage</code> value
     */
    void setStrategyMessage(StrategyMessage inStrategyMessage);
}
