//
// this file is automatically generated
//
package org.marketcetera.strategy;

/* $License$ */

/**
 * Identifies a unique strategy instance.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface HasStrategyInstance
{
    /**
     * Get the strategyinstance value.
     *
     * @return a <code>StrategyInstance</code> value
     */
    StrategyInstance getStrategyInstance();
    /**
     * Set the strategyinstance value.
     *
     * @param inStrategyInstance a <code>StrategyInstance</code> value
     */
    void setStrategyInstance(StrategyInstance inStrategyInstance);
}
