//
// this file is automatically generated
//
package org.marketcetera.strategy;

/* $License$ */

/**
 * Describes the state of a loaded strategy.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public enum StrategyStatus
{
    /**
     * strategy has been loaded and is not running
     */
    STOPPED,
    /**
     * strategy is running
     */
    RUNNING,
    /**
     * an error occurred trying to load or start the strategy
     */
    ERROR,
    /**
     * the strategy is in the process of loading
     */
    LOADING,
}
