//
// this file is automatically generated
//
package org.marketcetera.strategy;

import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.util.Collection;

import org.marketcetera.core.BaseClient;
import org.marketcetera.core.Preserve;

/* $License$ */

/**
 * Provides a client interface for StrategyRpc services.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@Preserve
public interface StrategyClient
        extends BaseClient
{
    /**
     * Requests loaded strategy instances.
     *
     * @returns a <code>Collection&lt;? extends StrategyInstance&gt;</code> value
     */
    Collection<? extends StrategyInstance> getStrategyInstances();
    /**
     * Load a new strategy instances.
     *
     * @param inStrategyInstance a <code>StrategyInstance</code> value
     * @returns an <code>StrategyStatus</code> value
     */
    StrategyStatus loadStrategyInstance(StrategyInstance inStrategyInstance);
    /**
     * 
     *
     *
     * @param inRequest
     * @throws IOException
     * @throws NoSuchAlgorithmException
     */
    void uploadFile(FileUploadRequest inRequest)
            throws IOException, NoSuchAlgorithmException;
}
