//
// this file is automatically generated
//
package org.marketcetera.strategy;

/* $License$ */

/**
 * Provides StrategyService services.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface StrategyService
{
    /**
     * Requests loaded strategy instances.
     *
     * @returns a <code>java.util.Collection<org.marketcetera.strategy.StrategyInstance></code> value
     */
    java.util.Collection<org.marketcetera.strategy.StrategyInstance> getStrategyInstances();
}
