//
// this file is automatically generated
//
package org.marketcetera.strategy;

import java.util.Date;

import org.marketcetera.admin.HasCurrentUser;
import org.marketcetera.core.Preserve;

/* $License$ */

/**
 * Identifies a unique strategy instance.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
@Preserve
public interface StrategyInstance
        extends HasCurrentUser
{
    /**
     * Get the name value.
     *
     * @return a <code>String</code> value
     */
    String getName();
    /**
     * Set the name value.
     *
     * @param inName a <code>String</code> value
     */
    void setName(String inName);
    /**
     * Get the filename value.
     *
     * @return a <code>String</code> value
     */
    String getFilename();
    /**
     * Set the filename value.
     *
     * @param inFilename a <code>String</code> value
     */
    void setFilename(String inFilename);
    /**
     * Get the hash value.
     *
     * @return a <code>String</code> value
     */
    String getHash();
    /**
     * Set the hash value.
     *
     * @param inHash a <code>String</code> value
     */
    void setHash(String inHash);
    /**
     * Get the nonce value.
     *
     * @return a <code>String</code> value
     */
    String getNonce();
    /**
     * Set the nonce value.
     *
     * @param inNonce a <code>String</code> value
     */
    void setNonce(String inNonce);
    /**
     * Get the started value.
     *
     * @return a <code>Date</code> value
     */
    Date getStarted();
    /**
     * Set the started value.
     *
     * @param inStarted a <code>Date</code> value
     */
    void setStarted(Date inStarted);
    /**
     * Get the status value.
     *
     * @return an <code>StrategyStatus</code> value
     */
    StrategyStatus getStatus();
    /**
     * Set the status value.
     *
     * @param inStatus an <code>StrategyStatus</code> value
     */
    void setStatus(StrategyStatus inStatus);
}
