//
// this file is automatically generated
//
package org.marketcetera.strategy;

/* $License$ */

/**
 * Creates new {@link StrategyInstance} objects.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public interface StrategyInstanceFactory
        extends org.marketcetera.core.Factory<StrategyInstance>
{
    /**
     * Create a new <code>StrategyInstance</code> instance.
     *
     * @return a <code>StrategyInstance</code> value
     */
    @Override
    StrategyInstance create();
    /**
     * Create a new <code>StrategyInstance</code> instance from the given object.
     *
     * @param inStrategyInstance a <code>StrategyInstance</code> value
     * @return a <code>StrategyInstance</code> value
     */
    @Override
    StrategyInstance create(StrategyInstance inStrategyInstance);
}
