//
// this file is automatically generated
//
package org.marketcetera.trade.pnl.event;

/* $License$ */

/**
 * Indicates that an existing position for a user has changed.
 *
 * @author <a href="mailto:colin@marketcetera.com">Colin DuPlantis</a>
 * @version $Id$
 * @since $Release$
 */
public class SimplePositionChangedEvent
        implements PositionChangedEvent
{
    /**
     * Create a new SimplePositionChangedEvent instance.
     */
    public SimplePositionChangedEvent() {}
    /**
     * Get the position value.
     *
     * @return a <code>org.marketcetera.trade.pnl.Position</code> value
     */
    @Override
    public org.marketcetera.trade.pnl.Position getPosition()
    {
        return position;
    }
    /**
     * Set the position value.
     *
     * @param inPosition a <code>org.marketcetera.trade.pnl.Position</code> value
     */
    public void setPosition(org.marketcetera.trade.pnl.Position inPosition)
    {
        position = inPosition;
    }
    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append("PositionChangedEvent [")
            .append("position=").append(position).append("]");
        return builder.toString();
    }
    /**
     * position which has changed
     */
    private org.marketcetera.trade.pnl.Position position;
}
