name: Java CI with Maven

on:
  push:
    branches: [ "main", "master", "develop", "java17-upgrade" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    # Debug Maven version and environment
    - name: Debug environment
      run: |
        mvn -version
        java -version
    
    # Build and test in a single step, no scripts needed
    - name: Build and test with Maven
      run: mvn -B clean package -Dmetc.jdbc.password=pw4metc -Dmetc.jdbc.driver=org.h2.Driver -Dmetc.jdbc.url=jdbc:h2:./target/metc -Dmetc.jdbc.testquery="select 1" -Dmetc.hibernate.dialect=org.hibernate.dialect.H2Dialect -Dmetc.flyway.vendor=h2
    
    # Upload artifacts
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: |
          **/target/*.jar
          !**/target/*-sources.jar
          !**/target/*-tests.jar