# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  metc.jdbc.user: metc
  metc.jdbc.password: pw4metc
  metc.jdbc.driver: org.hsqldb.jdbc.JDBCDriver
  metc.jdbc.url: jdbc:hsqldb:file:./target/data/metc-hsqldb-data
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
          distribution: 'temurin'
          java-version: '8'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package -Dmetc.skip.docker=true --file pom.xml
